### ISSUE TITLE
Deactivating accounts

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1148]
## Enhancement

I’m opening this issue to discuss details around deactivating accounts.

For consideration:

- [ ] Govern a privacy policy including account deactivation (offline as a team)
- [ ] Stripe implications (also see #1129 allowing a user to remove payment info)
- [ ] auth0 implications
- [ ] Organization implications (see #721)
- [ ] Team implications (perhaps see #1058)

**Estimated effort**: 18 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))
