### ISSUE TITLE
Epic 7 UI updates

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1397]
## Enhancement

Capturing a list of things to improve along the way:

- [x] Button sizing and typography updates
- [x] Form control sizing and typography updates
- [ ] `IconControl` replaced with flat button

**Estimated effort**: 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
deferring on `IconControl`
