### ISSUE TITLE
Epic 8 Acceptance Criteria

### ISSUE THREAD

**Issue by dan-f** [ParabolInc/action#1510]
# Epic 8 Acceptance Criteria *[Updated]*

This issue represents the set of acceptance criteria / user stories that must be implemented before epic 8 ships.

## New `@mention` and assignment notifications
- [ ] When my teammate and I are **not** in a meeting, and my teammate **assigns** me a project, I get a Notification and a Toast. The notification should indicate that I was **assigned** a project, and afford me to view the board on which the project exists.
- [ ] When my teammate and I are **not** in a meeting, and my teammate **mentions** me on a project, I get a Notification and a Toast. The notification should indicate that I was **mentioned** on a project, and afford me to view the board on which the project exists.
- [ ] When my teammate and I **are** in a meeting, and my teammate **assigns** me a project, I do not get a notification.
- [ ] When my teammate and I **are** in a meeting, and my teammate **mentions** me in a project, I do not get a notification.

## New notification UI/UX
- [ ] When I have unaddressed notifications from within the last 24 hours, and I have not been active in the app within the last 24 hours, I receive an email with the number of unread notifications I have. When I follow the link to "See My Notifications," I am sent to my notification dashboard.
- [ ] When I have unaddressed notifications, and I view the notifications screen, I am afforded a "clear all" button. When I click the "clear all" button, all my notifications are cleared which do not require action from me.
- [ ] Each notification type has an appropriate icon, copy, and actionable affordances.

@ackernaut - here are the acceptance stories for epic8. I think we've captured most of these in the various feature / sprint PRs, but I want to get a canonical list here before we merge & ship. Please add any stories which I omitted!

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by dan-f** [comment]
## New `@mention` and assignment notifications
- [x] When I am **not** in a meeting, and my teammate **assigns** me a project, I get a notification. The notification should indicate that I was **assigned** a project, and afford me to view the board on which the project exists.
- [x] When I am **not** in a meeting, and my teammate **mentions** me on a project, I get a notification. The notification should indicate that I was **mentioned** on a project, and afford me to view the board on which the project exists.
- [x] When I **am** in a meeting, and my teammate **assigns** me a project, I do not get a notification.
- [x] When I **am** in a meeting, and my teammate **mentions** me on a project, I do not get a notification.

## New notification UI/UX
- [ ] When I have unaddressed notifications from within the last 24 hours, and I have not been active in the app within the last 24 hours, I receive an email with the number of unread notifications I have. When I follow the link to "See My Notifications," I am sent to my notification dashboard.
- [ ] When I have unaddressed notifications, and I view the notifications screen, I am afforded a "clear all" button. When I click the "clear all" button, all my notifications are cleared which do not require action from me.
- [ ] Each notification type has an appropriate icon, copy, and actionable affordances.

**Comment by ackernaut** [comment]
@dan-f this looks good! I’ll join you and take a pass at this test on staging. It is helpful to put a “test cycle number” on the comment when you are completing the test, even though it can be inferred by who leaves the comment and when.

**Comment by ackernaut** [comment]
## Test Cycle No. 2 (TA) (in progress)
### New `@mention` and assignment notifications
- [ ] When I am **not** in a meeting, and my teammate **assigns** me a project, I get a notification. The notification should indicate that I was **assigned** a project, and afford me to view the board on which the project exists.
- [ ] When I am **not** in a meeting, and my teammate **mentions** me on a project, I get a notification. The notification should indicate that I was **mentioned** on a project, and afford me to view the board on which the project exists.
- [ ] When I **am** in a meeting, and my teammate **assigns** me a project, I do not get a notification.
- [ ] When I **am** in a meeting, and my teammate **mentions** me on a project, I do not get a notification.
- [ ] When I am **not** in a meeting, but my teammate **is**, and my teammate **assigns** me a project, I get a notification.
- [ ] When I am **not** in a meeting, but my teammate **is**, and my teammate **mentions** me in a project, I get a notification.

### New notification UI/UX
- [ ] When I have unaddressed notifications from within the last 24 hours, and I have not been active in the app within the last 24 hours, I receive an email with the number of unread notifications I have. When I follow the link to "See My Notifications," I am sent to my notification dashboard.
- [ ] When I have unaddressed notifications, and I view the notifications screen, I am afforded a "clear all" button. When I click the "clear all" button, all my notifications are cleared which do not require action from me.
- [ ] Each notification type has an appropriate icon, copy, and actionable affordances.

**Comment by dan-f** [comment]
# Test Cycle No. 2 [in progress]

This issue represents the set of acceptance criteria / user stories that must be implemented before epic 8 ships.

## New `@mention` and assignment notifications
- [ ] When I am **not** in a meeting, and my teammate **assigns** me a project, I get a Notification and a Toast. The notification should indicate that I was **assigned** a project, and afford me to view the board on which the project exists.
- [ ] When I am **not** in a meeting, and my teammate **mentions** me on a project, I get a Notification and a Toast. The notification should indicate that I was **mentioned** on a project, and afford me to view the board on which the project exists.
- [ ] When I **am** in a meeting, and my teammate **assigns** me a project, I get a Notification but not a Toast.
- [ ] When I **am** in a meeting, and my teammate **mentions** me on a project, I get a Notification but not a Toast.
- [ ] When I am **not** in a meeting, but my teammate **is**, and my teammate **assigns** me a project, I get a notification and a Toast.
- [ ] When I am **not** in a meeting, but my teammate **is**, and my teammate **mentions** me in a project, I get a notification and a Toast.

## New notification UI/UX
- [ ] When I have unaddressed notifications from within the last 24 hours, and I have not been active in the app within the last 24 hours, I receive an email with the number of unread notifications I have. When I follow the link to "See My Notifications," I am sent to my notification dashboard.
- [ ] When I have unaddressed notifications, and I view the notifications screen, I am afforded a "clear all" button. When I click the "clear all" button, all my notifications are cleared which do not require action from me.
- [ ] Each notification type has an appropriate icon, copy, and actionable affordances.

**Comment by dan-f** [comment]
# Test cycle no. 2 (in progress)

## New `@mention` and assignment notifications
- [x] When my teammate and I are **not** in a meeting, and my teammate **assigns** me a project, I get a Notification and a Toast. The notification should indicate that I was **assigned** a project, and afford me to view the board on which the project exists.
- [x] When my teammate and I are **not** in a meeting, and my teammate **mentions** me on a project, I get a Notification and a Toast. The notification should indicate that I was **mentioned** on a project, and afford me to view the board on which the project exists.
- [ ] When my teammate and I **are** in a meeting, and my teammate **assigns** me a project, I do not get a notification.
- [ ] When my teammate and I **are** in a meeting, and my teammate **mentions** me in a project, I do not get a notification.

## New notification UI/UX
- [ ] When I have unaddressed notifications from within the last 24 hours, and I have not been active in the app within the last 24 hours, I receive an email with the number of unread notifications I have. When I follow the link to "See My Notifications," I am sent to my notification dashboard.
- [ ] When I have unaddressed notifications, and I view the notifications screen, I am afforded a "clear all" button. When I click the "clear all" button, all my notifications are cleared which do not require action from me.
- [ ] Each notification type has an appropriate icon, copy, and actionable affordances.

@ackernaut - here are the acceptance stories for epic8. I think we've captured most of these in the various feature / sprint PRs, but I want to get a canonical list here before we merge & ship. Please add any stories which I omitted!

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))
