### ISSUE TITLE
Onboarding Check-In views

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1674]
### JTBD

>When on-boarding with Parabol, team leads want to understand both what on-boarding means and become familiar with the Check-In so that they can better use the meeting UX with their team.

#### Bertie’s Check-In
Users can:
  - [ ] See an initial check-in view from Bertie with copy about who Bertie is (just a scripted bot), what on-boarding is for (to learn how to have a better meeting), and how long it takes (3 phases in about 3-5 minutes)
  - [ ] See this view as soon as they sign up
  - [ ] Tap on “Let’s Begin!” to start
  - [ ] See meeting navigation that says “Onboarding” with an iconic button (with tooltip) to stop the on-boarding meeting (criteria and effort addressed in #1687)
  - [ ] Cannot see the agenda topic input during on-boarding check-in  (criteria and effort addressed in #1687)
  - [ ] Cannot see top-right meeting avatars during on-boarding check-in

#### Users’s Check-In
Users can:
  - [ ] See this after they see Bertie’s initial check-in view
  - [ ] See a prompt to submit their preferred name
  - [ ] Use a text input to type their preferred name (with placeholder text, etc.)
  - [ ] Optionally tap the default avatar to add their avatar
  - [ ] Press a button to move forward
  - [ ] See the first Bertie dialog box with messages (criteria, effort in #1673 #1683)
  - [ ] Cannot see top-right meeting avatars yet
  - [ ] Cannot see agenda topic input in nav yet

**Estimated effort**: 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Concepts**:

![check-in_ bertie](https://user-images.githubusercontent.com/307286/35461361-35d8cd3a-02ad-11e8-97be-57b1030a58f6.png)
![check-in_ marimar](https://user-images.githubusercontent.com/307286/35461362-3607074a-02ad-11e8-85cf-139a46d8a643.png)

**Comment by ackernaut** [comment]
Ice-boxing…
