### ISSUE TITLE
Meeting UI updated with new palette, lighter theme

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1675]
## Enhancement

Let’s update the meeting views to use the new palette, typeface and lighter look-and-feel!

### Acceptance Criteria

- [ ] Meeting UI theme and components updated in Figma
- [ ] Meeting sidebar nav has updated colors, typeface, and changes to state (active location of meeting progress, facilitator location, etc.)
- [ ] Meeting sidebar moves branding to bottom left
- [ ] Meeting sidebar header has team name, meeting link that can be copied (with tooltip hint), and a link that opens the team dash/hub in another tab
- [ ] Agenda list in sidebar updated (see criteria, effort in #1693)
- [ ] Meeting content has updated background, typeface, buttons, etc.
- [ ] Meeting prompts lose the clunky, rounded box. The type floats over the background.
- [ ] The meeting UI has updated avatars (see #1544)
- [ ] The meeting UI has a toolbar for facilitation (see criteria, effort in #1676)

**Estimated effort**: 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Closing, this is 85% done or broken into smaller issues — forgot about this issue! So many issues…I got issues!
