### ISSUE TITLE
Meeting Summary (general updates)

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1686]
## Enhancement

Let’s track general palette and style updates, copy updates, and content updates (adding Done, changing Stats, etc.)

### Acceptance Criteria

- [x] Adds new meeting-phase label style
- [x] Adds “Task(s) Done” quick stat #1034 
- [x] Consider removing “number of teammates present out of total” (##/##) quick stat
- [x] Adds a Done section per teammate #644
- [x] Distinguishes and labels the New task cards section per teammate
- [x] Clarifies presence (here/not here)
- [x] Clarifies users that didn’t get cards
- [x] Consider something helpful for #1000 (letting folks know Done column was archived)
- [x] Adds new palette, typography, and lighter, less-clunky theme

### Fixes
- #1648 
- #644 
- #1034 

**Estimated effort**: 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Shipped with #1731
