### ISSUE TITLE
Onboarding view animations

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1688]
## Enhancement

Let’s give a few visual cue as to what is going with content and Bertie.

### Acceptance Criteria

- [ ] Animate the top-prioritized active card in each updates view
- [ ] Consider animating the agenda topic input once when most relevant
- [ ] Show “Bertie is adding…” for agenda topics with perhaps slight animation (see #1428 and #1680 and #1693)
- [ ] Show “Bertie is adding…” for new tasks cards with perhaps slight animation (see #1681)
- [ ] Consider effort for general onboarding navigation needs (see #1687)

**Estimated effort**: 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Ice-boxing
