### ISSUE TITLE
Agenda topic list and input component updated

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1693]
## Enhancement

Let’s apply the new palette and lighter feel. Let’s consider some light navigation tensions. Let’s add some multiplayer magic.

### Acceptance Criteria

  - [ ] Users can see that an agenda topic is being added. Shows like an agenda topic item but says “PreferredName is adding…” or “PreferredName is adding a topic…” if width allows for that much text. (consider coordinating efforts with #1680)
  - [ ] Users can see a light background color for “current topic” state
  - [ ] Consider only attaching facilitator location dot to the phases
  - [ ] Users can see that the text is set to strike-through when processed
  - [ ] Consider removing the “quotes” from the topic text
  - [ ] Consider updating or removing local user location
  - [ ] Topics can still be navigated by a tap
  - [ ] Optionally: The agenda input component has the “current state” background styling when on Last Call
  - [ ] Consider moving the agenda input to the end of the list and pinning when overflow scroll in #1365 (there are other considerations about input focus)
  - [ ] Consider anything still relevant from #1428 

**Estimated effort**: 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Most of the theme updates will be taken care of in #1837 

Going to create a separate issue for the multiplayer effect in the first AC bullet.
