### ISSUE TITLE
Implement nudges to upgrade

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#1980]
This issue is for implementation of the output of the design cycles for #1879:

#### Note
- PR #2042 is only scoped to show upgrade CTAs to Billing Leaders
- Issue #2059 is a first step to showing BLs to all org members
- [ ] TBD: will have to capture other issues to implement other pieces of this
- See #2092 scoping some low-effort enhancements around org info and upgrade CTA to the team settings view

### Acceptance Criteria

- [x] The user hub menu has a CTA “Upgrade to PRO” on the Organizations menu item when 1 or more orgs to which the user is a member is on the Personal tier. IF the count is 1, then tapping it goes directly to the billing view (with role-based context, see below) for that org. IF the count is 2+, the user goes to the list of orgs.
- [x] The list of orgs has a CTA “Upgrade to PRO” on the row items for Personal orgs. The action routes the user to the billing view.
- [ ] The team dash has a CTA “Upgrade to PRO”, alongside the name of the org. The user goes to the billing view (with role-based context, see below). see #2101
- [ ] Any org member can reach the billing view, but we need to handle contexts:
  - Is Billing Leader, Is Paid: shows billing info and members (no change)
  - Is Billing Leader, Is Not Paid: shows nudge to upgrade (no change, except maybe aesthetic)
  - Is Org Member, Is Paid: show members (including clearly labeled Billing Leaders, see #1555) but no ability to change roles, can see tier, can leave org
  - Is Org Member, Is Not Paid: can nudge 1 or more billing leaders with a notification about interest in upgrading
- [ ] A notification is generated letting the Billing Leader know that Org Member would like to upgrade to Pro. The Org Member cannot notify the same Billing Leader again until the Billing Leader clears the notification. The notification has a message and 2 actions: the main action of Upgrade Now (or See Billing, label TBD), and the secondary action ✔️ (to clear and do nothing). Tapping the main action routes the user to the billing view. (see #2102)
- [ ] A user can leave an org (see #1431 )

#### Latest Concepts

[Clickable prototype](https://www.figma.com/proto/DXqOZNFNbfvkBBxvPCKgfiNW/Nudges-to-Upgrade?scaling=scale-down&node-id=1%3A2)

[File with various states](https://www.figma.com/file/DXqOZNFNbfvkBBxvPCKgfiNW/Nudges-to-Upgrade)

### Estimated Effort
13 points

**Comment by ackernaut** [comment]
Consider #1897 when working on this…

**Comment by ackernaut** [comment]
Started in Sprint No. 7

**Comment by ackernaut** [comment]
Note: the archive squeeze exposes billing leader info in presentation
![screenshot 2018-05-02 12 29 31](https://user-images.githubusercontent.com/307286/39539611-b9038904-4e05-11e8-9960-9e5cf3d6827b.png)

**Comment by ackernaut** [comment]
Going to break this down into smaller issues…

**Comment by ackernaut** [comment]
Closing this in favor of smaller issues: #2101, #2102, #1431, #2059, #2042, #2092
