### ISSUE TITLE
Testing for 1.8.0 release

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2079]
# Release Integration Test No. 1
**Status:** (passed locally on `master`)
​
## Tests:
​
### Authentication
- [x] Can login
- [x] Can logout
​
### Team Dashboard
- [x] Can navigate to Team Dashboard
- [x] Can create project on Team Dashboard
- [x] Can create 3 additional Projects on Team Dashboard
- [x] Can re-assign ownership of Project
- [x] Can resort priority among 3 Project Cards
- [x] Can assign new Project status via click
- [x] Can assign new Project status via drag
- [x] Can navigate to second team from Team Dashboard
- [x] Can create Project on second team
- [x] Can create 3 agenda items on Team Dashboard
- [x] Can reorder agenda items on Team Dashboard
​
### Team Dashboard > Archive
- [x] Can archive 1 Project Card
- [x] Can navigate to Archive
- [x] Can restore Project Card
​
### Team Dashboard > Settings
- [x] Can navigate to Team Settings
- [x] Can invite new user by email address
- [x] Can add Slack integration and channel
- [x] Can add GitHub integration and repository
​
### Accept Email Invitation
- [x] New user can accept email invitation
​
### Team Meeting
- [x] Can navigate to Meeting Lobby
- [x] Can see presence of second Team Member
- [x] Can start Meeting from Meeting Lobby
- [x] Can observe Slack meeting start notification on channel
- [x] Facilitator can lead meeting through Check-In
- [x] Can create Project Cards on Updates dashboard
- [x] Participant can follow, diverge and rejoin Facilitator
- [x] Participant can add agenda item
- [x] Can reorder agenda items
- [x] Facilitator can proceed to process Agenda Items
- [x] Participant can add Project card on Agenda Item
- [x] Participant can add second Project card on Agenda Item
- [x] Participant can promote second Project card to GitHub issue
- [x] Facilitator can proceed through Agenda Items to Last Call
- [x] Facilitator can end Meeting
- [x] All Participants can see Meeting Summary
- [x] All Participants receive email Meeting Summary
- [x] Can observe Slack meeting stop notification on channel
​
### Notifications
- [x] Can assign new other user, other user can see notification
- [x] Can @mention card to other user, other user can see noficiation
- [x] User can clear notifications
​
### My Dashboard
- [x] Can navigate to My Dashboard
- [x] Can reassign priority across teams from My Dashboard
​
### Team Dashboard > Settings > Manage Team
- [ ] Can remove Team Member
​
## Notes / New Issues
​
- #XXX: issue description...

**Comment by ackernaut** [comment]
Not sure these things are regressions, probably exist anyway:

- There was a hang up when removing another user from the team and it was that person’s only team. They could still see the view until reload. Tried inviting and kicking the same user from another team and the other user was redirected to My Dash which was the expected behavior.

- When I added a GH integration locally and navigated back to the team dashboard, I could not add a card and the error message included some method related to GH
- Locally I saw the squeeze in the archive, not sure if there is some funny logic going on there

**Comment by ackernaut** [comment]
# Release Integration Test No. 2
**Status:** (in progress on staging)
​
## Tests:
​
### Authentication
- [ ] Can login
- [ ] Can logout
​
### Team Dashboard
- [ ] Can navigate to Team Dashboard
- [ ] Can create project on Team Dashboard
- [ ] Can create 3 additional Projects on Team Dashboard
- [ ] Can re-assign ownership of Project
- [ ] Can resort priority among 3 Project Cards
- [ ] Can assign new Project status via click
- [ ] Can assign new Project status via drag
- [ ] Can navigate to second team from Team Dashboard
- [ ] Can create Project on second team
- [ ] Can create 3 agenda items on Team Dashboard
- [ ] Can reorder agenda items on Team Dashboard
​
### Cards
- [ ] Can add, edit, navigate to, and remove a link in a card
- [ ] Can format text (bold, italics, underline)
- [ ] Can add emoji
- [ ] Can mention a teammate
- [ ] Can add code, codeblock, quote content
​
### Team Dashboard > Archive
- [ ] Can archive 1 Project Card
- [ ] Can navigate to Archive
- [ ] Can restore Project Card
​
### Team Dashboard > Settings
- [ ] Can navigate to Team Settings
- [ ] Can invite new user by email address
- [ ] Can add Slack integration and channel
- [ ] Can add GitHub integration and repository
​
### Accept Email Invitation
- [ ] New user can accept email invitation
​
### Team Meeting
- [ ] Can navigate to Meeting Lobby
- [ ] Can see presence of second Team Member
- [ ] Can start Meeting from Meeting Lobby
- [ ] Can observe Slack meeting start notification on channel
- [ ] Facilitator can lead meeting through Check-In
- [ ] Can create Project Cards on Updates dashboard
- [ ] Participant can follow, diverge and rejoin Facilitator
- [ ] Participant can add agenda item
- [ ] Can reorder agenda items
- [ ] Facilitator can proceed to process Agenda Items
- [ ] Participant can add Project card on Agenda Item
- [ ] Participant can add second Project card on Agenda Item
- [ ] Participant can promote second Project card to GitHub issue
- [ ] Facilitator can proceed through Agenda Items to Last Call
- [ ] Facilitator can end Meeting
- [ ] All Participants can see Meeting Summary
- [ ] All Participants receive email Meeting Summary
- [ ] Can observe Slack meeting stop notification on channel
​
### To-do: add retro-specific checklist (TA)
​
### Notifications
- [ ] Can assign new other user, other user can see notification
- [ ] Can @mention card to other user, other user can see noficiation
- [ ] User can clear notifications
​
### My Dashboard
- [ ] Can navigate to My Dashboard
- [ ] Can reassign priority across teams from My Dashboard
​
### Team Dashboard > Settings > Manage Team
- [ ] Can remove Team Member
​
## Notes / New Issues
​
- #XXX: issue description...

**Comment by ackernaut** [comment]
integration test passed on staging, see previous comment
