### ISSUE TITLE
v1.9.0 release integration test on staging

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2118]
# Release Integration Test Checklist
**Status:** (TA, in progress)
​
## Tests:
​
### Authentication
- [x] Can sign up
- [x] Can sign in
- [x] Can sign out
- [x] Sees warning when login attempt with wrong creds
​
### Team Dashboard
- [x] Can navigate to Team Dashboard
- [x] Can create project on Team Dashboard
- [x] Can create 3 additional Projects on Team Dashboard
- [x] Can re-assign ownership of Project
- [x] Can resort priority among 3 Project Cards
- [x] Can assign new Project status via click
- [x] Can assign new Project status via drag
- [x] Can navigate to second team from Team Dashboard
- [x] Can create Project on second team
- [x] Can create 3 agenda items on Team Dashboard
- [x] Can reorder agenda items on Team Dashboard
​
### Cards
- [x] Can add, edit, navigate to, and remove a link in a card
- [x] Can format text (bold, italics, underline)
- [x] Can add emoji
- [x] Can mention a teammate
- [x] Can add code, codeblock, quote content
​
### Team Dashboard > Archive
- [x] Can archive 1 Project Card
- [x] Can navigate to Archive
- [x] Can restore Project Card
​
### Team Dashboard > Settings
- [x] Can navigate to Team Settings
- [x] Can invite new user by email address
- [x] Can add Slack integration and channel
- [x] Can add GitHub integration and repository
​
### Accept Email Invitation
- [x] New user can accept email invitation
​
### Team Meeting
- [x] Can navigate to Meeting Lobby
- [x] Can see presence of second Team Member
- [x] Can start Meeting from Meeting Lobby
- [x] Can observe Slack meeting start notification on channel
- [x] Facilitator can lead meeting through Check-In
- [x] Can create Project Cards on Updates dashboard
- [x] Participant can follow, diverge and rejoin Facilitator
- [x] Participant can add agenda item
- [x] Can reorder agenda items
- [x] Facilitator can proceed to process Agenda Items
- [x] Participant can add Project card on Agenda Item
- [x] Participant can add second Project card on Agenda Item
- [x] Participant can promote second Project card to GitHub issue
- [x] Facilitator can proceed through Agenda Items to Last Call
- [x] Facilitator can end Meeting
- [x] All Participants can see Meeting Summary
- [x] All Participants receive email Meeting Summary
- [x] Can observe Slack meeting stop notification on channel
​
### To-do: add retro-specific checklist (TA)
​
### Notifications
- [x] Can assign new other user, other user can see notification
- [x] Can @mention card to other user, other user can see noficiation
- [x] User can clear notifications
​
### My Dashboard
- [x] Can navigate to My Dashboard
- [x] Can reassign priority across teams from My Dashboard
​
### Team Dashboard > Settings > Manage Team
- [x] Can remove Team Member
​
### Test new changes
- [x] upgrade CTAs and billing views
- 🚫 (partial, see notes below) non-billing leader can leave organization from org > members view
- [x] end meeting button on Action meetings
- [x] auto-grouping: I saw 1 auto-group but then the button went away.
- [x] due dates on cards
- [x] empty reflections: I moved to Group with Facilitator, while another user had focused a new but empty reflection card. In the Group view I briefly saw the empty card but then it went away after a tick. Assuming that was the order of the rendering and filter of empty cards.
- [x] stacked reflections: I stacked a bunch and they seem to work as expected
- [ ] retro voting after teammate joins
- [x] strikethrough shortcut
- [x] not sure of an easy way to test the 1 letter email and name, but was able to test locally with success
- 🚫 can integrate with private Slack channel

## Notes / New Issues
​
- **Summary route edge case**: if User B stays on meeting summary route, and user A goes and has another meeting, once User A gets to the meeting summary again, there is the summary re-routing bug #1804 for User B, but they get an error because some data is not updated:
![screenshot 2018-05-09 11 43 06](https://user-images.githubusercontent.com/307286/39827975-197c62e6-537f-11e8-8f16-09633679cdf6.png)
- **Slack integrations for private channels**: (see #2120) seems like we have configured our integration to only work with public channels? Even so, I was able to attempt to integrate with a private channel from the Slack auth view from the dropdown under private heading. Also, when tapping “Remove Slack” and “Remove” (on channel row) I got errors in our own Slack integration view. Looks like #1964 and some other bugs cover general issues with this since the subscriptions haven’t been touched in a while.
![screenshot 2018-05-09 11 52 04](https://user-images.githubusercontent.com/307286/39828188-c69bf3c4-537f-11e8-9775-7ae2d0d0dbd8.png)
- **Non-BL leave organization**: (see #2121) I was unable to leave the organization when user was non-BL and on free-tier org. Nothing apparent in browser console. Button just showed the waiting state. This was the only org that this user was on. Can a user leave the only org they are on? Updated: I created a 2nd org with this user then tried to leave the first org where user was a non-BL. Still couldn’t leave. Updated again: after upgrading to Pro with the BL user, the non-BL user still can’t leave the org. Updated yet again: with a 3rd user who was non-BL on the org, I was able to leave the org. Not sure why it’s hanging up for user no. 2 on the org. Oh my the updates: 2nd user joined 3rd org, was able to leave the 3rd org, but still not able to leave the first org. 2nd user archived teams and is not on any teams for the 1st org. Still not able to leave first org.
- **Approving and accepting team invites**: (adding to #2114) I invited User A to Org B with User B. User A accepted then invited User C. User B approved and User C accepted. Team Settings view refreshed, but User C’s row only had the name, not the email. On hard refresh the info was there.
- **Subscription issue when archiving team?**: (#2122) When archiving a team the toast said: `null has been archived`. Tried archiving a different team with a different user. It seemed to go through, but instead of the left-nav item going away for that team, it was duplicated instead (2 instances). Went back to other user and successfully archived a team. I think it’s hit-or-miss based on subscriptions or connections. Did see a console error floating around, not sure if it is directly related, or happening in general but causing issues. `{message: "Subscription field must return Async Iterable. Received: [object Object]"}`. I wonder if it is a race condition. Sometimes I create and archive teams pretty quickly when testing.

- **Got stuck on Retro Vote view**: Steps:
  - made many cards between 2 different users on 2 different devices (to interrupt and check empty card filter during Group view)
  - auto-grouped once (then the button disappeared)
  - created a big group with the remaining cards that weren’t autogrouped
  - then moved ALL the cards to one big group
  - went to vote stage and seeing this for both users, even on hard refresh of URL:
![screenshot 2018-05-09 12 35 41](https://user-images.githubusercontent.com/307286/39830103-10a3cf86-5386-11e8-958f-2b6c8b2e117e.png)

**Comment by jordanh** [comment]
# Smoke check v1.9.0-2
- [x] retro voting after team member joins
- [x] vote phase reflection card exception regression

GTG!
