### ISSUE TITLE
Integration test checklist for release v2.2.0

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2170]
# Release Integration Test Checklist
**Status:** (in progress)

### Authentication
- [x] Can sign up
- [x] Can sign in
- [x] Can sign out
- [x] Sees warning when login attempt with wrong creds
​
### Team Dashboard
- [x] Can navigate to Team Dashboard
- [x] Can create a Task Card on Team Dashboard
- [x] Can create 3 additional Task Cards on Team Dashboard
- [x] Can re-assign ownership of Task Card
- [x] Can resort priority among 3 Task Cards
- [x] Can assign new Task status via click
- [x] Can assign new Task status via drag
- [x] Can navigate to second team from Team Dashboard
- [x] Can create Task Card on second team
- [x] Can create 3 Agenda Topics on Team Dashboard
- [x] Can reorder Agenda Topics on Team Dashboard
- [x] Can invite a new teammate from the Assign Owner menu on a Task Card
​
### Task Card Content
- [x] Can add, edit, navigate to, and remove a link in a Task card
- [x] Can format text (bold, italics, underline, strikethrough [press ? for formatting options])
- [x] Can add emoji
- [x] Can mention a teammate
- [x] Can add #private tag by typing/using inline menu
- [x] Can add #archived tag by typing/using inline menu
- [x] Can add code, codeblock, quote content
​
### Team Dashboard > Archive
- [x] Can archive 1 Task Card
- [x] Can navigate to Archive
- [x] Can restore Task Card
​
### Team Dashboard > Settings
- [x] Can navigate to Team Settings
- [x] Can invite new user by email address
- [x] Can add Slack integration and channel
- [ ] Can add GitHub integration and repository
​
### Accept Email Invitation
- [x] New user can accept email invitation
​
### Team Meeting
- [x] Can navigate to Meeting Lobby
- [x] Can see presence of second Team Member
- [x] Can start Meeting from Meeting Lobby
- [x] Can observe Slack meeting start notification on channel
- [x] Facilitator can lead meeting through Check-In
- [x] Can create Task Cards on Updates dashboard
- [x] Participant can follow, diverge and rejoin Facilitator
- [x] Participant can add Agenda Topic
- [x] Can reorder Agenda Topics
- [x] Facilitator can proceed to process Agenda Topics
- [x] Participant can add Task Card on Agenda Topic
- [x] Participant can add second Task Card on Agenda Topic
- [x] Participant can promote second Task Card to GitHub issue
- [x] Participant can assign a new Task Card to another teammate
- [x] Can invite a new teammate from the Assign Owner menu on a Task Card
- [x] Facilitator can proceed through Agenda Topics to Last Call
- [x] Facilitator can end Meeting
- [x] All Participants can see Meeting Summary
- [x] All Participants receive email Meeting Summary
- [x] Can observe Slack meeting stop notification on channel
​
### Retro
- [x] 1 user can start the retro
- [x] The facilitator can complete the Check-In phase
- [x] 2 users can add reflection cards
- [x] 2 users can group
- [x] 2 users can vote
- [x] 2 users can add tasks during the Discuss phase
- [x] The facilitator can end the meeting
- [x] Users can see summary in browser
- [x] Users receive summary email
​
### Notifications
- [x] Can assign new other user, other user can see notification
- [x] Can @mention card to other user, other user can see noficiation
- [x] User can clear notifications
​
### My Dashboard
- [x] Can navigate to My Dashboard
- [x] Can reassign priority across teams from My Dashboard
​
### Team Dashboard > Settings > Manage Team
- [x] Can remove Team Member
​​
### Duckies on invite corner case

I ran into a frustrating user invite experience while testing this evening. Here are the steps:

1. `User A` invites `User B` by email address using Card soft invite affordance, `User B` does not have an active Parabol account
2. Open email invite for `User B`, paste into new incognito window
3. Click Sign Up link on Login Page
4. _Intentionally type the email address of a user that already exists` (e.g. `User A`'s address)
5. Correct email address by typing new address
6. Note that modal says invite is expired (TODO create low priority bug)
7. From `User A`'s browser, click on Team Settings and reinvite `User B`
8. Note, no notification but email is sent (TODO create low priority bug)
9. Sign out of `User B`'s browser
10. Paste signup link into `User B`'s incognito browser
11. Sign in as `User B` and note duckies forever (TODO create bug)
12. Manually navigate to `/signout` route. Sign in. Note `User B` can no longer sign in and gets duckies forever!

### Cannot click on emoji from menu to add it to Card

Repro steps:

1. Create a new task card
2. Type some text then type `:smi` and use the mouse cursor to select desired emoji (TODO: open bug)

**Comment by jordanh** [comment]
Bugs #2178  and #2179 opened
