### ISSUE TITLE
v2.4.0 integration test on staging

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2233]
# Release Integration Test Checklist
**Status:** (in progress on staging TA)
✋ indicates required manual test

### Authentication
- [x] ✋ Can sign up with username/password
- [ ] Can sign up with OAuth
- [x] ✋ Can sign in with username/password
- [x] ✋ Can sign in with OAuth
- [x] ✋ Can sign out
- [ ] Can reset password
- [ ] Sees warning when login attempt with wrong creds

### Welcome
- [x] User can add preferred name
- [x] User can add team name
- [ ] User can skip inviting others
- [x] User can add emails to invite
- [ ] User can remove an invite before sending
- [ ] User can add another invite before sending
- [x] User can complete sending invites to others (and verify that each invite is sent in team settings)

### Team Dashboard
- [x] ✋ Can navigate to Team Dashboard
- [x] ✋ Can create a Task Card on Team Dashboard
- [x] ✋ Can create 3 additional Task Cards on Team Dashboard
- [x] ✋ Can re-assign ownership of Task Card
- [x] ✋ Can resort priority among 3 Task Cards
- [x] ✋ Can assign new Task status via drag
- [x] ✋ Can navigate to second team from Team Dashboard (see New Team Form checklist)
- [x] ✋ Can create Task Card on second team
- [x] ✋ Can create 3 Agenda Topics on Team Dashboard
- [x] ✋ Can reorder Agenda Topics on Team Dashboard
- [ ] Can filter tasks by team member via filter menu
- [ ] Can filter tasks by text via search input
- [x] ✋ Can navigate to Action Meeting Lobby
- [x] ✋ Can navigate to Retro Meeting Lobby
- [ ] Can navigate to Organization

### Task Card Actions
- [ ] Can invite a new teammate from the Assign Owner menu on a Task Card
- [x] ✋ Can assign new Task status via click (vertical ellipsis toggles task menu)
- [ ] Can add a due date
- [ ] Can change a due date
- [ ] Can remove a due date
- [ ] Can toggle #private via task menu option
- [x] ✋ Can set as #archived via task menu option

### Task Card Content
- [x] ✋ Can add, update, and remove unformatted text
- [ ] Can add a link in a Task card via link editor menu
- [ ] Can edit text and URL of link in a Task card via link editor menu
- [ ] Can navigate to link in an unfocused Task card by tapping the link
- [ ] Can navigate to link in a Task card by using the link viewer menu
- [ ] Can remove a link in a Task card via link viewer menu
- [ ] Can format text (bold, italics, underline, strikethrough [press ? for formatting options])
- [ ] Can add emoji
- [ ] Can mention a teammate
- [ ] Can add #private tag by typing/using inline menu
- [x] ✋ Can add #archived tag by typing/using inline menu
- [ ] Can add code, codeblock, quote content

### Team Dashboard > Archive
- [x] ✋ Can archive 1 Task Card
- [x] ✋ Can navigate to Archive
- [x] ✋ Can restore Task Card

### Team Dashboard > Settings
- [x] ✋ Can navigate to Team Settings
- [ ] Can update name of team
- [ ] Can navigate to Upgrade via primary button when free
- [x] ✋ Can invite new user by email address
- [ ] Can cancel an invite inline
- [ ] Can resend an invite inline
- [ ] Can cancel a pending approval
- [x] ✋ Team Lead can remove a Team Member
- [ ] Team Lead can promote a Team Member to Team Lead
- [ ] Team Member can leave the team
- [ ] Can archive team
- [x] ✋ Can add Slack integration and channel
- [x] ✋ Can add GitHub integration and repository

### Slack Integration
- [ ] Can refresh token
- [ ] Can remove Slack
- [ ] Can remove added channel

### GitHub Integration (optional until we address issues)
- [ ] Can refresh token
- [ ] Can remove GitHub
- [ ] Can view external link to added repository
- [ ] Can link account to added repository

### New Team Form
- [x] Can navigate to New Team form
- [x] Can select to add new team to an existing organization
- [ ] Can select to add new team to a new organization
- [ ] Can add new organization name if selected
- [x] Can add a team name
- [ ] Can optionally invite team members by email
- [x] Can create team without error
- [ ] Can navigate to external link (Learn More)

### Accept Email Invitation
- [x] ✋ New user (username/password) can accept email invitation
- [ ] Existing user (username/password) can accept email invitation
- [ ] New user (OAuth) can accept email invitation
- [ ] Existing user (OAuth) can accept email invitation

### Action Meeting
- [x] ✋ Can navigate to Meeting Lobby
- [ ] Can copy, paste, and navigate to the meeting link
- [x] ✋ Can see presence of second Team Member
- [ ] Can access help menu (lower right) per view (lobby, check-in, updates, first call, agenda items, last call)
- [x] ✋ Can start Meeting from Meeting Lobby
- [x] ✋ Can observe Slack meeting start notification on channel
- [x] ✋ Facilitator can lead meeting through Check-In
- [x] ✋ Can create Task Cards on Updates dashboard
- [x] ✋ Participant can follow, diverge and rejoin Facilitator
- [x] ✋ Participant can add Agenda Topic
- [x] ✋ Can reorder Agenda Topics
- [x] ✋ Facilitator can proceed to process Agenda Topics
- [ ] Participant can request to become Facilitator
- [ ] Facilitator can grant request to participant to become the new Facilitator
- [x] ✋ Participant can add Task Card on Agenda Topic
- [x] ✋ Participant can add second Task Card on Agenda Topic
- [x] ✋ Participant can promote second Task Card to GitHub issue
- [ ] Participant can assign a new Task Card to another teammate
- [ ] Participant can add a due date in this phase
- [ ] Can invite a new teammate from the Assign Owner menu on a Task Card
- [x] ✋ Facilitator can proceed through Agenda Topics to Last Call
- [x] ✋ Facilitator can end meeting from Last Call view
- [ ] Facilitator can end meeting with End Meeting button
- [x] ✋ All Participants can see Meeting Summary in the browser
- [x] ✋ All Participants receive email Meeting Summary
- [x] ✋ Can observe Slack meeting stop notification on channel

### Meeting Summary
- [x] User can navigate to Team Dashboard from summary for Action or Retro

### Retro Meeting
- [x] Can navigate to the lobby
- [ ] Can access help menu (lower right) per view (lobby, check-in, reflect, group, vote, discuss)
- [ ] Can copy, paste, and navigate to the meeting link
- [x] 1 user can start the retro
- [x] The facilitator can complete the Check-In phase
- [x] 2 users can add reflection cards
- [x] 2 users can group
- [x] Can update the label of a group
- [x] The magical Auto Group button works
- [x] 2 users can vote
- [x] 2 users can add tasks during the Discuss phase
- [x] Can drag and drop to update the order of discussion topics
- [x] The facilitator can end the meeting
- [x] Users can see summary in browser
- [x] Users receive summary email

### Notifications
**Note**: notifications can be acted upon in toasts, these items do not address this UX yet
- [x] ✋ Task involves: users see a notification when they are assigned a task by a teammate outside of the meeting. The user can navigate to team dash or clear inline.
- [x] ✋ Task involves: users see a notification when they are mentioned in a task by a teammate outside of the meeting. The user can navigate to team dash or clear inline.
- [ ] Team member invited: users new to team receive a notification for team invite and can accept inline
- [ ] Team archived: when a team lead archives a team, team members receive a notification and can clear it inline
- [ ] Requested new user: billing leader receives a notification when another user requests a new user and can accept
- [ ] Requested new user: billing leader receives a notification when another user requests a new user and can decline (and the reason modal works)
- [ ] Denied new user: users receive a notification when the billing leader rejects a new user invite that has the reason why and it can be cleared inline
- [ ] Approved new user: users who sent an invite receive a notification when the billing leader approves that can be cleared
- [ ] Added to the team: when a user who has left a team is invited again, they are added immediately. That user gets a notification that can be cleared inline
- [ ] Payment rejected: when an org is paid and the payment info is not valid for some reason, the billing leader gets a notification stating there is an issue with a button that takes them to the billing view. It does not clear until the payment issue is cleared up (probably by updating credit card information). [this is not simple to test manually but is documented here TA]
- [ ] Promoted to Billing Leader: users are notified when they are promoted to the Billing Leader role of an organization. They have a control to navigate the organization (that works) and can clear the notification
- [ ] Removed from team: users receive a notificaiton when they are removed from a team with the ability to clear inline
- [x] ✋ User can clear all notification types that do not require action (team archived, denied new user, approved new user, added to the team, promoted to billing leader, removed from team) with a single button

### My Dashboard
- [x] ✋ Can navigate to My Dashboard
- [x] ✋ Can reassign priority across teams from My Dashboard (task column order)
- [ ] Can reassign a Task from 1 team to another team
- [ ] Can filter tasks by team via filter menu
- [ ] Can filter tasks by text via search input

### User Settings
- [x] Can update name
- [ ] Can add avatar
- [ ] Can update avatar

#### List view
- [ ] Users can see the organizations they belong to and navigate to
- [ ] Users see an Upgrade CTA for orgs that are on the free plan
- [ ] Users see which organizations are Pro
- [ ] Users can create a new org (loads New Team form with new org option selected)
#### Org Info
- [ ] Billing Lead can update name of organization
#### Billing view (when free)
- [ ] Billing Leaders see an upgrade squeeze that launches the credit card modal, an inline estimation, and an external link to pricing
- [ ] The modal to add a credit card works and also gives inline validation when there are errors
- [ ] Non-Billing Leaders see an upgrade squeeze to contact their Billing Leaders and an external link to pricing
#### Billing view (when paid)
- [ ] Billing Leaders can update credit card info via model
- [ ] Billing Leaders can load and view individual invoices including a current estimation
- [ ] Billing Leaders can contact to cancel Pro plan
- [ ] Non-Billing Leaders can’t access this view
#### Members view
- [ ] Billing Leaders can promote others to Billing Leader
- [ ] Billing Leaders can remove the Billing Leader role from others
- [ ] Billing Leaders can remove the Billing Leader from themselves when there is at least 1 other Billing Leader
- [ ] Billing Leaders can leave the organization when there is at least 1 other Billing Leader
- [ ] Billing Leaders can remove others from the Organization, including other Billing Leaders
- [ ] Billing Leaders can toggle user activity per spec when paid
- [ ] Billing Leaders are indicated with a badge
- [ ] Members can leave the organization
### Contextual Upgrading
- [ ] In the archive users see a squeeze when there are cards more than 2 weeks old. Billing Leaders see and can use a button to Upgrade. Other members see a main billing leader with email address. There is an external pricing link.
- [x] In the Retro lobby users see a squeeze based on a limit of 3 free retros. Billing Leaders can open the modal, fill out the credit card form, and close the modal from the confirmation view. Non-Billing Leaders can open and see a list of Billing Leaders to contact.

### Test New Changes (optional)
- [ ] Something new or fixed is working
- [ ] Something new or fixed is working
- [ ] Something new or fixed is working

## Notes / New Issues

- Scrubbed/created issue: #XXX issue description...
- I have issues when trying to use my Parabol email and OAuth but I think it’s an ongoing issue with my user, not the functionality of the auth. I am able to log in using OAuth with a different account. Not sure of a good way to sign up using OAuth without creating new email accounts or removing my OAuth users from staging (latest prod) data so that I can sign up again.
- [x] Fixed borked style for `TaskDragLayer`
- [x] Scrubbed/created issue: #2234 when removing a team member from a team, the team lead should see that the person is removed immediately (from the list of team members, from the top-right group of avatars, etc.)
- [x] Scrubbed/created issue: #2235 task card drag-n-drop over editor (verified this is already a bug on production, and does not break or block user experience, so non-critical) [internally see Sentry](https://sentry.io/parabol/action-staging/issues/591933546/)
