### ISSUE TITLE
Shadow elevation style system

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2298]
## Issue - Enhancement

To standardize the way we use elevations and shadows in the product, we need a list of constants that we can apply as styles to our various elevated components. AC follows:

### Acceptance Criteria (optional)
A developer can:
   - Use a file that contains a list of 1..n (25?) shadow elevation styles
   - Can apply these elevations from this file to components, then we can declare:
      - A component is flat (0 dp) or,
      - When raised, it is raised by n dp

The following components are updated to use and test these elevation styles:
   - [x] Reflection cards
   - [ ] Reflection groups (see comment below and #2331)
   - [ ] The help ? (see comment below and #2332)

- [x] And, an issue enumerating other components to update is created (see #2324) 

See: https://material-components.github.io/material-components-web-catalog/#/component/elevation

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Some updates and some questions here:
### Updates
- I added **an Elevation story** in #2248 (compare to [Material default values](https://material-components.github.io/material-components-web-catalog/#/component/elevation))
![screenshot 2018-08-15 15 59 49](https://user-images.githubusercontent.com/307286/44172983-48b98a80-a0a4-11e8-8d55-3c816481c86a.png)
- I added the equivalent as **Team Library components** [to Figma](https://www.figma.com/file/UAT8GVK86KVKdycX8xtK3tmM/UI-elevation?node-id=0%3A1) (note: I customized these from the unofficial Material Design Theme Kit in Figma [[our copy](https://www.figma.com/file/3wc6Vnbo0kufHBbk1VQvHV/Material-Design-Theme-Kit-Copy?node-id=0%3A1)], and Figma does not let you dial in `spread-radius` as the final CSS does.)
- **Reflection cards** are using resting (1dp, when in a grid or editing) and raised (8dp, when dragging) shadows
- Created an issue for deprecation details around using elevation and a working list of components to update (see #2324)
### Questions
- **Reflection groups** are contained in a custom modal without a backdrop. We have to design the animation to including raising the modal box aka adding the box-shadow. How should we handle the timing? We could add the box-shadow to the modal outer container or the modal background. The outer container hides any overflow including a nested element with box-shadow. The background is animated and the box-shadow should be based on its presentation, not the outer container. We could delay and transition in the box-shadow to the outer container once the background has finished its animation. See with ([http://recordit.co/LIsm36qtKi](http://recordit.co/LIsm36qtKi)) and without ([http://recordit.co/LIsm36qtKi](http://recordit.co/LIsm36qtKi)) adding a box-shadow (default Material, 24dp) to the outer container. Shall we add the group modal to this list (see #2324) and remove from this AC? I’ll play with this more, but don’t want to spend too much time.
- **Help button**: we should consider updating `BaseButton` to handle specific elevation values ([see comment](https://github.com/ParabolInc/action/pull/2248#issuecomment-405666782)) before addressing the FAB ( ? ) button of the meeting help menu. Shall we add the floating buttons to this list (see #2324) and remove from this AC? I’ll play with this some more, too.

@mattkrick

**Comment by mattkrick** [comment]
- Reflection Groups: we can animate during. that'll make it look like as it expands. i'll do this in its own PR since it's not like the others.
- aside from the reflection groups, I've got no strong opinion on what issue the refactors are attached to, so i'll follow your lead

**Comment by mattkrick** [comment]
ready for me to review right now
