### ISSUE TITLE
Demo route meta overridden, default meta updated

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2509]
### Jobs to Be Done

When I'm a search engine, I want to index the Parabol demo for what it is, so that folks can find it.

When I share a link to Parabol via Slack, I want the unrolled description to be relevant, so that it'll make me look smart and intrigue others to evaluate it

#### Default meta updated:

```Parabol is a free online retrospective tool featuring custom templates, powerful analytics, multi-user grouping, rich text editing, integrations, and gorgeous meeting summaries. Tasks are assigned and tracked so your team can continuously improve.```

#### Meta for `/retrospective-demo` updated:

```
Try Parabol without creating an account; a free online retrospective tool featuring custom templates, powerful analytics, multi-user grouping, rich text editing, integrations, and gorgeous meeting summaries. Tasks are assigned and tracked so your team can continuously improve.
```

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
### Updated AC:

- [ ] helmet meta + description properties removed
- [ ] meta tag defined for `https://action.parabol.co/retrospective-demo`
- [ ] default meta tag defined for `https://action.parabol.co/(signin|create-account)` and all other app routes

Meta tags implemented as `<meta property="description" content="" ...>`

### Design:

#### meta tag definition for `https://action.parabol.co/retrospective-demo`

```
See how Parabol makes for effective sprint retrospectives in 3 minutes or less, no account needed. Simulated colleagues illustrate Parabol's powerful features including multi-user grouping, rich text editing, and gorgeous meeting summaries. 
```

N.B. The first sentence is for SEO – `effective sprint retrospectives` is the keyphrase.

#### meta tag definition for all other app routes

```
Parabol is a free online retrospective tool. Try it without creating an account. Parabol features custom templates, powerful analytics, multi-user grouping, rich text editing, integrations, and gorgeous meeting summaries. Tasks are assigned and tracked so your team can continuously improve.
```

N.B. `free online retrospective` is for SEO.

**Comment by mattkrick** [comment]
"See how Parabol makes for effective sprint retrospectives" feels a little awkward outta the mouth, no? could just be me
