### ISSUE TITLE
Add slack integration for async meetings

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2802]
I think slack notifications for individuals who haven't completed it yet should be a thing, too. Maybe if you haven't participated in a certain phase & there is 1 hour left & the max time limit is > 1 hour, then we send a private message to an individual. we cannot safely @-mention them in the slack channel because anonymity. not sure how to execute yet, so marking OOS for now.

AC
- [ ] in the date/time picker ~modal~ menu, there is a pre-checked checkbox that says "Send Slack notification".
- [ ] When checked, a notification is sent to the slack channel of choice saying "The Async Retro for Team X has [started/advanced to the X Phase]. It will stay open for Y days, Z hours to complete it. [url]" see #2921 
- [ ] if the facilitator does not have a Slack integration, the box is not pre-checked.
- [ ] if the facilitator checks the box and no slack Oauth key exists, an Oauth window pops up (Slack asks which channel to include)
  - [ ] Since the facilitator is connecting to Slack now, their personal notification is set to come to their @ my Slack user channel per #2924 
- [ ] if the facilitator checks the box and 1 Slack channel is tied to the team, then the box shows as checked
  - [ ] ~if the facilitator checks the box and 2+ channels are tied to the team, a dropdown box appears asking which channel to use~ we are moving to a model where there is one channel applied to all team notifs or each notif gets a channel, but only 1 channel, [see target UI](https://www.figma.com/file/aFFwcgvkGJhjwQlMUxB4g3Zt?node-id=493%3A4&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#6855842)

Effort 12 points

**Comment by jordanh** [comment]
@ackernaut may we close this in favor of #2921 and #2924 ?

**Comment by ackernaut** [comment]
Yes, both link back to this in the AC
