### ISSUE TITLE
Add Async Retro Meeting

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2803]
- [ ] A Meeting Dash Alert appears when an async meeting is in progress
- [ ] An Async Retro Meeting is available in the Start Meeting dropdown
- [ ] Synchronous meetings are ended after 24 hours, async meetings are never auto-ended by a cron job (maybe don't do #2796)
- [ ] A modal pops up at the beginning of each phase for the facilitator
- [ ] The modal includes a Date & Time Picker to set the time when the meeting will auto advance. The default is 24 hours from now.
- [ ] The modal has a "no date" secondary action to never auto advance
- [ ] The modal has an affordance for a slack integration (OOS for this issue, see #2802)
- [ ] A new facilitator is not picked when the facilitator is not online
- [ ] The meeting footer has a countdown (OOS for this issue, see #2804)
- [ ] The control to advance does not bounce
- [ ] The checkin round does not exist. As a proxy for participants, anyone who visits any phase is marked as present (presence during reflect/group determines the votes remaining)
- [ ] The phase complete heuristics are updated to the following:
  - [ ] The reflect phase is only likely complete if every team member is present (has visited reflect phase) and has at least 1 reflection.
  - [ ] The group phase heuristic does not exist
  - [ ] The vote phase heuristic does not change

Effort: 12 points

**Comment by ackernaut** [comment]
I’d expect that anybody who first arrives during reflect, group, or vote can vote. I’d expect that anybody who arrives at any phase will be marked as present. There may be many reasons that they didn’t participate in the first 2 phases but end up showing up during vote, and have valid tensions on the team. Same for async discussion.

**Comment by mattkrick** [comment]
@ackernaut @jordanh one of the requirements was that a team can have 1 async meeting going at the same time as a sync meeting (eg quarterly retro async, sprint retro now).

can a team have unlimited meetings of any kind running at the same time? can they only have 1 meeting of 1 type? can they only have 1 async and 1 sync meeting?

**Comment by ackernaut** [comment]
My initial thought is that we should lean toward flexibility over rigidity. The only counter to that is if the effort to do so is greater and we could learn faster with something a little bit clunkier.

I think the simple OOUX is a user can start a thing, now thing exists. Maybe the lobby exists outside of the meeting and shows all the things that exists of that type. Maybe that is too stupid.

Retro Lobby -> List of active meetings (1 sync with guests, 1 async) etc.

It’s easier to make a case for retros, hard to make a case for action meeting. But if we offer a general format meeting, maybe there is only 1 meeting lobby for all types. List of active meetings (1 sync retro with guests, 1 async retro in group phase for 2 more days, 1 EOS level 10 started 30 mins ago). Then the user joins a meeting (unless they joined via a direct link, bypassing the lobby).

**Comment by ackernaut** [comment]
Each active meeting item could have it’s meta inline: who’s connected, when did it start, what phase, is there an active timebox, are there guests?) etc.

**Comment by ackernaut** [comment]
Perhaps each meeting is like a channel, it can be created and persist if desired

**Comment by mattkrick** [comment]
that's good perspective. IMO that flexibility is sacrificing a bunch of simplicity. if folks need concurrent meetings, they can make a new team. That way teams are the channels, not meetings.

i'd argue at most 1 synchronous meeting can be run at a time, because no one can be 2 places at once & if there is no overlap in participants, it should probably be 2 teams.

as for async, i'd love to limit it to 1, but the  quarterly retro/sprint retro  use case is too compelling.

can we start with 2 async meetings and 1 sync? we can keep the async limit flexible, but i'd like to keep it easy to see what should have their focus when they log in.

**Comment by ackernaut** [comment]
I like the perspective you give, too. I was just going for a design stretch in my mind since comments are cheap. Yeah, teammates shouldn’t be in 2 places at once (double-booked), but the nature of an ongoing async activity allows them to participate at will, so I could see that an async retro with a specific purpose (eg. how was last S.P.A. — you gotta week to get your reflections in) would happen outside of any sync rhythm.

A bigger question in my mind is: do we have both async and sync types, or 1 retro with an optional async mode on, or do we design 1 retro to have flexible affordances by default (skip check-in, use date timebox, etc.).

In most cases above, I wonder if we can only have 1 Action meeting running, and any number of Retros running. Or only 1 Action and 1 Retro that is not async mode or async type, otherwise any number of async mode/type Retros could be started. However, realistically folks probably don’t have that much use case for unlimited concurrent Retros. So I’m ok with what you propose: 2 async retro and 1 sync retro (and I assume 1 sync Action/EOS).

IMO we need to probably just yank the meeting modal that blocks the team dash view, and leave the banner/alert pattern or whatever better pattern we switch to over time.

I’m still not sure if we should have Retro async type, Retro async mode, or Retro flexible by default

**Comment by jordanh** [comment]
I think we should learn from some past experience: we've erred on the side of strict facilitation even over freedom. If we do meetings as channels (which I think is a great idea), I think we should avoid adding specific business logic that limits who many meetings folks can have open. Let's let the system of people police that at first, not us

**Comment by ackernaut** [comment]
[See Figma concept](https://www.figma.com/file/NBLSKRPK1cEtySuCwMevdXos?node-id=33%3A2&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#6280105)

**Comment by mattkrick** [comment]
- Simplicity over flexibility. If they select async from the get go, we know we can skip the check-in, skip the minutes timer, add discussion comments. If they select async after a phase begins, it's not an async meeting, it's an async _phase_. That's powerful, but I don't think that extra power warrants the sacrifice of simplicity. 

- I also want async action meetings. record your updates in a video like loom.

- Yes to removing the block on the team dash, that is gonna be really complex, but that's for later.


as you said, with multiple meetings we'll need to rethink lobby. let's imagine 2 intents: creating a meeting and joining a meeting.

To create a meeting, I can
- Click the start meeting button

To join a meeting, I can
- Click the start meeting button
- Click a permalink (slack, calendar, etc.)
- Click an in-app notification (redirect to permalink)

since the start meeting button serves 2 uses, we'll need a `/:meetingType/start` route that shows the meetings in progress, as well as button to start a new meeting.

when someone visits the permalink `/:meetingType` we should see how many meetings of that type are running. if 0, redirect to `/start`. if 1, redirect to `/:meetingId`. if 2+, show a list.

Of course that means the meetings themselves will not be permalinks, but redirects will work fine.

**Comment by mattkrick** [comment]
If a team has multiple meetings of the same type, there's no way to have a permalink (ie stick a link in the calendar, it always drops you in the meeting). we could still do that for sync meetings, but the logic feels brittle, so we should probably just make it the same for everything.

best we can do is permalink to a place where they can easily click the meeting they want to join.

after a meeting is created, we can announce a meeting link. we point directly to the meeting from in-app announcements.

the only tricky part is we have a permalink from the lobby. we can turn this into a feature by allowing folks to name the meeting & then having that be the slug. allowing folks to name their meetings feels right. 

maybe we do away with the lobby altogether? we have a team dash that looks like the integrations page. it shows a list of active meetings and below that a list of the kind of meetings you can start. each card also has meeting options (eg retro template). The challenge is keeping a new meeting 3 clicks away

**Comment by ackernaut** [comment]
I think I like the idea of encouraging (or requiring??) users to add an explicit name/topic to a meeting (and therefore slug) b/c I really feel folks will want exact permalinks pointed to the place they expect to land.

**Comment by ackernaut** [comment]
>I also want async action meetings. record your updates in a video like loom.

Yeah, I could see this as a useful mode for a daily stand-up.

**Comment by mattkrick** [comment]
> I think I like the idea of encouraging (or requiring??) users to add an explicit name/topic to a meeting (and therefore slug) b/c I really feel folks will want exact permalinks pointed to the place they expect to land.

right, the only problem is you don't get permalinks until it's meeting time. if folks put a meeting in a recurring calendar invite, where should that take them? My thought is somewhere where starting their meeting is 1 click away, so probably a list of possible meetings to start. Do we build that into the team dash, or do we create a new omni-meeting lobby?

**Comment by ackernaut** [comment]
[More user feedback about async UX](https://github.com/ParabolInc/action/issues/2775#issuecomment-491344157)

**Comment by ackernaut** [comment]
Closing for more issues in async milestone

**Comment by jordanh** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/2358351) gave this feedback:

> The other issue we noticed was that a retro seemed to have a 24hr life, we like to create them early so people can add topics as they come up throughout the sprint.
