### ISSUE TITLE
Release tests v3.9.0

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#2856]
# Release Integration Test Checklist
**Status:** (in progress/completed)
✋ indicates required manual test

### Authentication
- [x] ✋ Can create an account with username/password
- [x] Can create an account with OAuth
- [x] ✋ Can sign in with username/password
- [x] ✋ Can sign in with OAuth
- [x] ✋ Can sign out
- [x] Can reset password
- [x] Sees warning when login attempt with wrong creds

### Team Dashboard
- [x] ✋ Can navigate to Team Dashboard
- [x] ✋ Can create a Task Card on Team Dashboard
- [x] ✋ Can create 3 additional Task Cards on Team Dashboard
- [x] ✋ Can re-assign ownership of Task Card
- [x] ✋ Can resort priority among 3 Task Cards
- [x] ✋ Can assign new Task status via drag
- [x] ✋ Can navigate to second team from Team Dashboard (see New Team Form checklist)
- [x] ✋ Can create Task Card on second team
- [x] ✋ Can create 3 Agenda Topics on Team Dashboard
- [x] ✋ Can reorder Agenda Topics on Team Dashboard
- [x] Can filter tasks by team member via filter menu
- [x] Can filter tasks by text via search input
- [x] ✋ Can navigate to Action Meeting Lobby
- [x] ✋ Can navigate to Retro Meeting Lobby
- [x] Can navigate to Organization

### Task Card Actions
- [x] ✋ Can assign new Task status via click (vertical ellipsis toggles task menu)
- [x] Can add a due date
- [x] Can change a due date
- [x] Can remove a due date
- [x] Can toggle #private via task menu option
- [x] ✋ Can set as #archived via task menu option

### Task Card Content
- [x] ✋ Can add, update, and remove unformatted text
- [x] Can add a link in a Task card via link editor menu
- [x] Can edit text and URL of link in a Task card via link editor menu
- [x] Can navigate to link in an unfocused Task card by tapping the link
- [x] Can navigate to link in a Task card by using the link viewer menu
- [x] Can remove a link in a Task card via link viewer menu
- [x] Can format text (bold, italics, underline, strikethrough [press ? for formatting options])
- [x] Can add emoji
- [x] Can mention a teammate
- [x] Can add #private tag by typing/using inline menu
- [x] ✋ Can add #archived tag by typing/using inline menu
- [x] Can add code, codeblock, quote content

### Team Dashboard > Archive
- [x] ✋ Can archive 1 Task Card
- [x] ✋ Can navigate to Archive
- [x] ✋ Can restore Task Card

### Team Dashboard > Settings
- [x] ✋ Can navigate to Team Settings
- [x] Can update name of team
- [x] Can navigate to Upgrade via primary button when free
- [ ] Can archive team
- [x] ✋ Can add Slack integration and channel
- [ ] Can add GitHub integration and repository

### Slack Integration
- [ ] Can refresh token
- [ ] Can remove Slack
- [ ] Can remove added channel

### GitHub Integration (optional until we address issues)
- [ ] Can refresh token
- [ ] Can remove GitHub
- [ ] Can view external link to added repository
- [ ] Can link account to added repository

### Team Member Management
- [ ] Go to the Team Dashboard, tapping an avatar opens a menu
- [ ] As a Team Lead, you can promote someone else to Team Lead
- [ ] as a Team Lead, you can remove someone from the team and that user gets a toast
- [ ] As a non-Team Lead, you can leave the team from the avatar menu
- [ ] Team Lead has a badge

### New Team Form
- [x] Can navigate to New Team form
- [x] Can select to add new team to an existing organization
- [x] Can select to add new team to a new organization
- [x] Can add new organization name if selected
- [x] Can add a team name
- [x] Can create team without error
- [ ] Can navigate to external link (Learn More)
- [ ] Organizations on the free tier can only have up to 10 teams

### Team Invitations
- [ ] The control (+) to invite teammates is accessible from the Team Dashboard
- [ ] The control (+) to invite teammates is accessible from meeting views
- [ ] Tapping the control (+) pops a modal allowing users to type in a list of comma-separated email addresses (better handling is OOS)
- [ ] Email addresses of existing team members trigger an error on the client
- [ ] On success, the content of the modal changes showing the email addresses that received an invite. It goes away on click out or after 5 seconds
- [ ] If the recipient is a logged-in Parabol user, they get both a toast and a notification in real time
- [ ] Email addresses of existing team members/duplicates are silently ignored on the server
- [ ] Duplicates are silently ignored

### Accept Invitation by Notification
- [ ] Tapping to accept on the toast accepts and navigates to the new team’s dashboard
- [ ] Tapping to accept on the notification accepts and navigates to the new team’s dashboard
- [ ] Accepting removes the notification and any other notifications that invite the user to that team
- [ ] An invitation accepted by notification should NOT expire. Otherwise we'd have to cron-job notifications. We know it was accepted by notification if they are a user and they provided the notification id with the token
- [ ] After accepting by notification, if the token from the email is used, it’s registered as already accepted 

### Accept Invitation by Email /team-invitation/:token
- [ ] If token is invalid, goes to token not found page
- [ ] If token already accepted, goes to already accepted page
- [ ] If token already expired, goes to already expired page
- [ ] If logged in, accepts automatically and goes to team dash
- [ ] If existing Parabol user using Google Oauth, goes to Google sign-in
- [ ] If existing Parabol user and not using Google Oauth, goes to email/password sign-in
- [ ] If new user and we detect a Google MX record, goes to Google sign-up
- [ ] If at the Google sign-up and the user doesn’t want to use Google, they can click to use an email/password
- [ ] If new user and we do NOT detectx a Google MX record, goes to email/password sign-up
- [ ] If email sign-up and an existing email/password is entered, it’s silently treated like a login
- [ ] If user accepts invitation to team while team has a Retro Meeting in progress, the new team member’s avatar appears in the meeting and participants can navigate to the new team members’s check-in phase

### Action Meeting
- [x] ✋ Smoke test the Action Meeting through to summary
- [ ] Can navigate to Meeting Lobby
- [ ] Can copy, paste, and navigate to the meeting link
- [ ] Can see presence of second Team Member
- [ ] Can access help menu (lower right) per view (lobby, check-in, updates, first call, agenda items, last call)
- [ ] Can start Meeting from Meeting Lobby
- [ ] Can observe Slack meeting start notification on channel
- [ ] Facilitator can lead meeting through Check-In
- [ ] Can create Task Cards on Updates dashboard
- [ ] Participant can follow, diverge and rejoin Facilitator
- [ ] Participant can add Agenda Topic
- [ ] Can reorder Agenda Topics
- [ ] Facilitator can proceed to process Agenda Topics
- [ ] Participant can request to become Facilitator
- [ ] Facilitator can grant request to participant to become the new Facilitator
- [ ] Participant can add Task Card on Agenda Topic
- [ ] Participant can add second Task Card on Agenda Topic
- [ ] Participant can promote second Task Card to GitHub issue
- [ ] Participant can assign a new Task Card to another teammate
- [ ] Participant can add a due date in this phase
- [ ] Can invite a new teammate from the Assign Owner menu on a Task Card
- [ ] Facilitator can proceed through Agenda Topics to Last Call
- [ ] Facilitator can end meeting from Last Call view
- [ ] Facilitator can end meeting with End Meeting button
- [ ] All Participants can see Meeting Summary in the browser
- [ ] All Participants receive email Meeting Summary
- [ ] Can observe Slack meeting stop notification on channel

### Meeting Summary
- [ ] User can navigate to Team Dashboard from summary for Action or Retro

### Retro Meeting
- [x] ✋ Smoke test the Retro Meeting through to summary
- [ ] Can navigate to the lobby
- [ ] Can access help menu (lower right) per view (lobby, check-in, reflect, group, vote, discuss)
- [ ] Can copy, paste, and navigate to the meeting link
- [ ] Can select a prompt template (see [complete list of tests](https://github.com/ParabolInc/action/pull/2366#issue-213787896))
- [ ] Can customize prompt templates (see [complete list of tests](https://github.com/ParabolInc/action/pull/2366#issue-213787896))
- [ ] 1 user can start the retro
- [ ] The facilitator can complete the Check-In phase
- [ ] 2 users can add reflection cards
- [ ] 2 users can group
- [ ] Can update the label of a group
- [ ] The magical Auto Group button works
- [ ] 2 users can vote
- [ ] 2 users can add tasks during the Discuss phase
- [ ] Can drag and drop to update the order of discussion topics
- [ ] The facilitator can end the meeting
- [ ] Users can see summary in browser
- [ ] Users receive summary email

### Retro Summary
- [ ] User can download the CSV from the browser summary view

### Retro Demo
- [x] Guest user can advance through all phases
- [x] Guest user sees scripted bot interactions in all phases
- [x] Guest user can interact in all phases
- [x] Guest user receives a sample summary
- TK More granular checklist than the items above

### Notifications
**Note**: notifications can be acted upon in toasts, these items do not address this UX yet
- [x] ✋ Task involves: users see a notification when they are assigned a task by a teammate outside of the meeting. The user can navigate to team dash or clear inline.
- [x] ✋ Task involves: users see a notification when they are mentioned in a task by a teammate outside of the meeting. The user can navigate to team dash or clear inline.
- [ ] Team member invited: users new to team receive a notification for team invite and can accept inline
- [ ] Team archived: when a team lead archives a team, team members receive a notification and can clear it inline
- [ ] Requested new user: billing leader receives a notification when another user requests a new user and can accept
- [ ] Requested new user: billing leader receives a notification when another user requests a new user and can decline (and the reason modal works)
- [ ] Denied new user: users receive a notification when the billing leader rejects a new user invite that has the reason why and it can be cleared inline
- [ ] Approved new user: users who sent an invite receive a notification when the billing leader approves that can be cleared
- [ ] Added to the team: when a user who has left a team is invited again, they are added immediately. That user gets a notification that can be cleared inline
- [ ] Payment rejected: when an org is paid and the payment info is not valid for some reason, the billing leader gets a notification stating there is an issue with a button that takes them to the billing view. It does not clear until the payment issue is cleared up (probably by updating credit card information). [this is not simple to test manually but is documented here TA]
- [ ] Promoted to Billing Leader: users are notified when they are promoted to the Billing Leader role of an organization. They have a control to navigate the organization (that works) and can clear the notification
- [ ] Removed from team: users receive a notification when they are removed from a team with the ability to clear inline
- [x] ✋ User can clear all notification types that do not require action (team archived, denied new user, approved new user, added to the team, promoted to billing leader, removed from team) with a single button

### My Dashboard
- [x] ✋ Can navigate to My Dashboard
- [x] ✋ Can reassign priority across teams from My Dashboard (task column order)
- [x] Can reassign a Task from 1 team to another team
- [ ] Can filter tasks by team via filter menu (lost this with timeline)
- [ ] Can filter tasks by text via search input (lost this with timeline)

### User Settings
- [ ] Can update name
- [ ] Can add avatar
- [ ] Can update avatar

#### List view
- [ ] Users can see the organizations they belong to and navigate to
- [ ] Users see an Upgrade CTA for orgs that are on the free plan
- [ ] Users see which organizations are Pro
- [ ] Users can create a new org (loads New Team form with new org option selected)

#### Org Info
- [ ] Billing Lead can update name of organization

#### Billing view (when free)
- [x] ✋ Billing Leaders see an upgrade squeeze that launches the credit card modal, an inline estimation, and an external link to pricing
- [x] ✋ The modal to add a credit card works and also gives inline validation when there are errors
- [ ] Non-Billing Leaders see an upgrade squeeze to contact their Billing Leaders and an external link to pricing

#### Billing view (when paid)
- [ ] Billing Leaders can update credit card info via model
- [ ] Billing Leaders can load and view individual invoices including a current estimation
- [ ] Billing Leaders can contact to cancel Pro plan
- [ ] Non-Billing Leaders can’t access this view

#### Invoice
- [ ] Shows active users, and applicable cost
- [ ] Shows adjustments for new users who were added
- [ ] Shows adjustments for users who were paused and unpaused
- [ ] Shows adjustments for users who were removed from or left the organization

#### Organization Admin via GraphQL Interface
- [ ] In admin/graphql, the mutation `downgradeToPersonal` works
- [ ] In admin/graphql, the query `suOrgCount` works
- [ ] In admin/graphql, the query `suUserCount` works
- [ ] In admin/graphql, the query `suProOrgInfo` works

#### Members view
- [ ] Billing Leaders can promote others to Billing Leader
- [ ] Billing Leaders can remove the Billing Leader role from others
- [ ] Billing Leaders can remove the Billing Leader from themselves when there is at least 1 other Billing Leader
- [ ] Billing Leaders can leave the organization when there is at least 1 other Billing Leader
- [ ] Billing Leaders can remove others from the Organization, including other Billing Leaders
- [ ] Billing Leaders can pause a user when on the Pro tier
- [ ] Billing Leaders are indicated with a badge
- [ ] An organization user is paused automatically after 30 days of inactivity
- [ ] Members can leave the organization
- [ ] New users are added to the organization when they are invited to a team of that organization

### Test New Changes (optional)
- [x] Can add/edit on Android when content has plain text and/or emoji only

**Comment by ackernaut** [comment]
## Notes / New Issues
- Relay error subscribing to tasks during agenda (player A connected card to Atlassian, player B connected card to GitHub, player B’s view didn’t update when player A kept adding task cards) also happened during Retro discuss. When player A created Jira card the other 2 players subscription stopped updating (didn’t see Jira card or additional task card from Player A until refresh) seems to work fine for GitHub, just borks with Jira
![Screenshot 2019-05-01 12 08 09](https://user-images.githubusercontent.com/307286/57031698-032af680-6c0e-11e9-85e7-a1fd372496b4.png)
- Have to do hard refresh to get recently used in card integration menu when first adding an integration
- Had a CTA card on timeline to start an action meeting for “Newest Team” but wasn’t on a team called “Newest Team” when clicking through got blank dev error screen b/c no team exists
![Screenshot 2019-05-01 12 23 32](https://user-images.githubusercontent.com/307286/57031709-0b833180-6c0e-11e9-8022-27c4819134dd.png)
- (Can’t reproduce) Player B on dash got error when player A was in Retro lobby editing a template. Player B didn’t get meeting alert with Player A started retro meeting.
![Screenshot 2019-05-01 12 11 54](https://user-images.githubusercontent.com/307286/57031725-14740300-6c0e-11e9-8349-72681871db90.png)
- Due date pill disappears on hover, but still clickable
- Probably race condition ending action meeting saw `Cannot read property 'scrollIntoView' of null
    at AgendaItem.js:82`
- Link back to sign in with new password #2857
- TD captured android/mobile reflect group modal (needs to center in viewport, not over prompt columns)
- TD improve menu width change when searching integrations
- TD Revisited card width during drag
- TD Error messaging in link editor has wonky layout
- TD Android fields z-index over backdrop or something when side nav drawer open

**Comment by mattkrick** [comment]
> Have to do hard refresh to get recently used in card integration menu when first adding an integration

can you describe the repro & the actual result? is it nothing? is it the list of all items?

**Comment by mattkrick** [comment]
> Relay error subscribing to tasks during agenda

fixed!

> Have to do hard refresh to get recently used in card integration menu when first adding an integration

can't repro

> Had a CTA card on timeline to start an action meeting for “Newest Team” 

Looks like that was your onboarding team, i've got a feeling that it's account-specific since we remove suggested actions when a team is archived

**Comment by ackernaut** [comment]
@mattkrick 
- Yes, as we discussed, the GitHub menu list doesn’t refresh right away because it hasn’t been written yet, so no blocker there
- I see that the realtime interactions are fixed with Relay and new Jira cards, but do see a console message `TaskSubscription case fail CreateJiraIssuePayload`
- Yeah, I think I probably had bad data with my staging user re: timeline CTA and missing team

**Comment by ackernaut** [comment]
Issues created!
