### ISSUE TITLE
Release v4.1.0

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#3111]
# Release Integration Test Checklist
**Status:** (in progress/completed)
✋ indicates required manual test

### Authentication
- [x] ✋ Can create an account with username/password
- [ ] Can create an account with OAuth
- [x] ✋ Can sign in with username/password
- [x] ✋ Can sign in with OAuth
- [x] ✋ Can sign out
- [ ] Can reset password
- [ ] Sees warning when login attempt with wrong creds

### Team Dashboard
- [x] ✋ Can navigate to Team Dashboard
- [x] ✋ Can create a Task Card on Team Dashboard
- [x] ✋ Can create 3 additional Task Cards on Team Dashboard
- [x] ✋ Can re-assign ownership of Task Card
- [x] ✋ Can resort priority among 3 Task Cards
- [x] ✋ Can assign new Task status via drag
- [x] ✋ Can navigate to second team from Team Dashboard (see New Team Form checklist)
- [x] ✋ Can create Task Card on second team
- [x] ✋ Can create 3 Agenda Topics on Team Dashboard
- [x] ✋ Can reorder Agenda Topics on Team Dashboard
- [x] Can filter tasks by team member via filter menu
- [x] Can filter tasks by text via search input
- [x] ✋ Can navigate to Action Meeting Lobby
- [x] ✋ Can navigate to Retro Meeting Lobby
- [x] Can navigate to Organization

### Task Card Actions
- [x] ✋ Can assign new Task status via click (vertical ellipsis toggles task menu)
- [x] Can add a due date
- [x] Can change a due date
- [x] Can remove a due date
- [x] Can toggle #private via task menu option
- [x] ✋ Can set as #archived via task menu option
- [x] Can publish card context as GitHub issue
- [x] Can publish card context as Jira issue

### Task Card Content
- [x] ✋ Can add, update, and remove unformatted text
- [x] Can add a link in a Task card via link editor menu
- [x] Can edit text and URL of link in a Task card via link editor menu
- [x] Can navigate to link in an unfocused Task card by tapping the link
- [x] Can navigate to link in a Task card by using the link viewer menu
- [x] Can remove a link in a Task card via link viewer menu
- [x] Can format text (bold, italics, underline, strikethrough [press ? for formatting options])
- [x] Can add emoji
- [x] Can mention a teammate
- [x] Can add #private tag by typing/using inline menu
- [x] ✋ Can add #archived tag by typing/using inline menu
- [x] Can add code, codeblock, quote content
- [x] Can add/edit on Android when content has plain text and/or emoji only

### Team Dashboard > Archive
- [x] ✋ Can archive 1 Task Card
- [x] ✋ Can navigate to Archive
- [x] ✋ Can restore Task Card

### Team Dashboard > Settings
- [x] ✋ Can navigate to Team Settings
- [x] Can update name of team
- [x] Can navigate to Upgrade via primary button when free
- [x] Can archive team

### Atlassian Integration
- [x] Can connect Atlassian
- [ ] Can refresh token
- [x] Can remove Atlassian

### Slack Integration
- [x] ✋ Can connect Slack integration
- [ ] Can refresh token
- [x] Can remove Slack
- [ ] Can change team channel
- [ ] Can toggle team notifications
- [ ] Can change personal channel
- [ ] Can toggle personal notifications

### GitHub Integration
- [x] Can connect GitHub
- [ ] Can refresh token
- [x] Can remove GitHub

### Team Member Management
- [x] Go to the Team Dashboard, tapping an avatar opens a menu
- [x] As a Team Lead, you can promote someone else to Team Lead
- [x] as a Team Lead, you can remove someone from the team and that user gets a toast
- [x] As a non-Team Lead, you can leave the team from the avatar menu
- [x] Team Lead has a badge

### New Team Form
- [x] Can navigate to New Team form
- [x] Can select to add new team to an existing organization
- [x] Can select to add new team to a new organization
- [x] Can add new organization name if selected
- [x] Can add a team name
- [x] Can create team without error
- [x] Can navigate to external link (Learn More)
- [ ] Organizations on the free tier can only have up to 10 teams

### Team Invitations
- [ ] The control (+) to invite teammates is accessible from the Team Dashboard
- [ ] The control (+) to invite teammates is accessible from meeting views
- [ ] Tapping the control (+) pops a modal allowing users to type in a list of comma-separated email addresses (better handling is OOS)
- [ ] Email addresses of existing team members trigger an error on the client
- [ ] On success, the content of the modal changes showing the email addresses that received an invite. It goes away on click out or after 5 seconds
- [ ] If the recipient is a logged-in Parabol user, they get both a toast and a notification in real time
- [ ] Email addresses of existing team members/duplicates are silently ignored on the server
- [ ] Duplicates are silently ignored
- [x] An invite link that last for 1 day can be copied and shared. Other users can hit the link and sign up or sign in, and are added to the team.

### Accept Invitation by Notification
- [ ] Tapping to accept on the toast accepts and navigates to the new team’s dashboard
- [ ] Tapping to accept on the notification accepts and navigates to the new team’s dashboard
- [ ] Accepting removes the notification and any other notifications that invite the user to that team
- [ ] An invitation accepted by notification should NOT expire. Otherwise we'd have to cron-job notifications. We know it was accepted by notification if they are a user and they provided the notification id with the token
- [ ] After accepting by notification, if the token from the email is used, it’s registered as already accepted 

### Accept Invitation by Email /team-invitation/:token
- [ ] If token is invalid, goes to token not found page
- [ ] If token already accepted, goes to already accepted page
- [ ] If token already expired, goes to already expired page
- [ ] If logged in, accepts automatically and goes to team dash
- [ ] If existing Parabol user using Google Oauth, goes to Google sign-in
- [ ] If existing Parabol user and not using Google Oauth, goes to email/password sign-in
- [ ] If new user and we detect a Google MX record, goes to Google sign-up
- [ ] If at the Google sign-up and the user doesn’t want to use Google, they can click to use an email/password
- [ ] If new user and we do NOT detectx a Google MX record, goes to email/password sign-up
- [ ] If email sign-up and an existing email/password is entered, it’s silently treated like a login
- [ ] If user accepts invitation to team while team has a Retro Meeting in progress, the new team member’s avatar appears in the meeting and participants can navigate to the new team members’s check-in phase

### Action Meeting
- [x] ✋ Smoke test the Action Meeting through to summary
- [ ] Can navigate to Meeting Lobby
- [ ] Can copy, paste, and navigate to the meeting link
- [ ] Can see presence of second Team Member
- [ ] Can access help menu (lower right) per view (lobby, check-in, updates, first call, agenda items, last call)
- [ ] Can start Meeting from Meeting Lobby
- [ ] Can observe Slack meeting start notification on channel
- [ ] Facilitator can lead meeting through Check-In
- [ ] Can create Task Cards on Updates dashboard
- [ ] Participant can follow, diverge and rejoin Facilitator
- [ ] Participant can add Agenda Topic
- [ ] Can reorder Agenda Topics
- [ ] Facilitator can proceed to process Agenda Topics
- [ ] Participant can request to become Facilitator
- [ ] Facilitator can grant request to participant to become the new Facilitator
- [ ] Participant can add Task Card on Agenda Topic
- [ ] Participant can add second Task Card on Agenda Topic
- [ ] Participant can promote second Task Card to GitHub issue
- [ ] Participant can assign a new Task Card to another teammate
- [ ] Participant can add a due date in this phase
- [ ] Can invite a new teammate from the Assign Owner menu on a Task Card
- [ ] Facilitator can proceed through Agenda Topics to Last Call
- [ ] Facilitator can end meeting from Last Call view
- [ ] Facilitator can end meeting with End Meeting button
- [ ] All Participants can see Meeting Summary in the browser
- [ ] All Participants receive email Meeting Summary
- [ ] Can observe Slack meeting stop notification on channel

### Meeting Summary
- [ ] User can navigate to Team Dashboard from summary for Action or Retro

### Retro Meeting
- [x] ✋ Smoke test the Retro Meeting through to summary
- [ ] Can navigate to the lobby
- [ ] Can access help menu (lower right) per view (lobby, check-in, reflect, group, vote, discuss)
- [ ] Can copy, paste, and navigate to the meeting link
- [ ] Can select a prompt template (see [complete list of tests](https://github.com/ParabolInc/action/pull/2366#issue-213787896))
- [ ] Can customize prompt templates (see [complete list of tests](https://github.com/ParabolInc/action/pull/2366#issue-213787896))
- [ ] 1 user can start the retro
- [ ] The facilitator can complete the Check-In phase
- [ ] 2 users can add reflection cards
- [ ] 2 users can group
- [ ] Can update the label of a group
- [ ] The magical Auto Group button works
- [ ] 2 users can vote
- [ ] 2 users can add tasks during the Discuss phase
- [ ] Can drag and drop to update the order of discussion topics
- [ ] The facilitator can end the meeting
- [ ] Users can see summary in browser
- [ ] Users receive summary email

### Retro Summary
- [ ] User can download the CSV from the browser summary view

### Retro Demo
- [x] ✋ Smoke tested Demo
- [ ] Guest user can advance through all phases
- [ ] Guest user sees scripted bot interactions in all phases
- [ ] Guest user can interact in all phases
- [ ] Guest user receives a sample summary
- TK More granular checklist than the items above

### Notifications
**Note**: notifications can be acted upon in toasts, these items do not address this UX yet
- [x] ✋ Task involves: users see a notification when they are assigned a task by a teammate outside of the meeting. The user can navigate to team dash or clear inline.
- [x] ✋ Task involves: users see a notification when they are mentioned in a task by a teammate outside of the meeting. The user can navigate to team dash or clear inline.
- [ ] Team member invited: users new to team receive a notification for team invite and can accept inline
- [ ] Team archived: when a team lead archives a team, team members receive a notification and can clear it inline
- [ ] Payment rejected: when an org is paid and the payment info is not valid for some reason, the billing leader gets a notification stating there is an issue with a button that takes them to the billing view. It does not clear until the payment issue is cleared up (probably by updating credit card information). [this is not simple to test manually but is documented here TA]
- [ ] Promoted to Billing Leader: users are notified when they are promoted to the Billing Leader role of an organization. They have a control to navigate the organization (that works) and can clear the notification
- [ ] Removed from team: users receive a notification when they are removed from a team with the ability to clear inline
- [ ] Meeting phase end TK behavior description
- [x] ✋ User can clear all notification types that do not require action (team archived, denied new user, approved new user, added to the team, promoted to billing leader, removed from team) with a single button

### My Dashboard
- [x] ✋ Can navigate to My Dashboard
- [x] ✋ Can reassign priority across teams from My Dashboard (task column order)
- [ ] Can reassign a Task from 1 team to another team
- [ ] Can filter tasks by team via filter menu (lost this with timeline)
- [ ] Can filter tasks by text via search input (lost this with timeline)

### My Timeline
- [ ] Can click to summary from meeting history card (including summaries for teams that the user is no longer on)
- [ ] Can click on CTA card if conditions apply
- [ ] Can click to feature post when feature updates card is there

### User Settings
- [x] Can update name
- [ ] Can add avatar
- [ ] Can update avatar

#### List view
- [ ] Users can see the organizations they belong to and navigate to
- [ ] Users see an Upgrade CTA for orgs that are on the free plan
- [ ] Users see which organizations are Pro
- [ ] Users can create a new org (loads New Team form with new org option selected)

#### Org Info
- [x] Billing Lead can update name of organization

#### Billing view (when free)
- [x] ✋ Billing Leaders see an upgrade squeeze that launches the credit card modal, an inline estimation, and an external link to pricing
- [x] ✋ The modal to add a credit card works and also gives inline validation when there are errors
- [ ] Non-Billing Leaders see an upgrade squeeze to contact their Billing Leaders and an external link to pricing

#### Billing view (when paid)
- [ ] Billing Leaders can update credit card info via model
- [ ] Billing Leaders can load and view individual invoices including a current estimation
- [ ] Billing Leaders can contact to cancel Pro plan
- [ ] Non-Billing Leaders can’t access this view

#### Invoice
- [x] Shows active users, and applicable cost
- [ ] Shows adjustments for new users who were added
- [ ] Shows adjustments for users who were paused and unpaused
- [ ] Shows adjustments for users who were removed from or left the organization

#### Organization Admin via GraphQL Interface
- [ ] In admin/graphql, the mutation `downgradeToPersonal` works
- [ ] In admin/graphql, the query `suOrgCount` works
- [ ] In admin/graphql, the query `suUserCount` works
- [ ] In admin/graphql, the query `suProOrgInfo` works

#### Members view
- [ ] Billing Leaders can promote others to Billing Leader
- [ ] Billing Leaders can remove the Billing Leader role from others
- [ ] Billing Leaders can remove the Billing Leader from themselves when there is at least 1 other Billing Leader
- [ ] Billing Leaders can leave the organization when there is at least 1 other Billing Leader
- [ ] Billing Leaders can remove others from the Organization, including other Billing Leaders
- [ ] Billing Leaders can pause a user when on the Pro tier
- [ ] Billing Leaders are indicated with a badge
- [ ] An organization user is paused automatically after 30 days of inactivity
- [ ] Members can leave the organization
- [ ] New users are added to the organization when they are invited to a team of that organization

### Test New Changes (optional)
- [ ] Something new or fixed is working
- [ ] Something new or fixed is working
- [ ] Something new or fixed is working

## Notes / New Issues

- Scrubbed/created issue: #XXX issue description...

**Comment by ackernaut** [comment]
### Integrations view not scrollable
Go to Team > Integrations. Add Slack in a shorter viewport, note that you can’t scroll to see all of the Slack card/panel.

**Comment by ackernaut** [comment]
### Team dash layout on mobile
While clunky, this used to be scrollable. Now the components are squished or clipped out of the viewport. Most notably, can‘t start a meeting. I know that primarily using this on a mobile is not the main case anyway, but we’re capturing and making progress against that. Not sure if there’s a quick fix, may need to prioritize a design issue sooner than later.

![Screenshot 2019-08-16 11 08 11](https://user-images.githubusercontent.com/307286/63181760-6d797280-c016-11e9-94b2-7880e6bacb72.png)

**Comment by ackernaut** [comment]
### Joining teams quickly, flashing team/invite URL
Invite another user to 2 teams by email. With the other user, accept the 1st invite from the notifications view, then quickly navigate to the notifications view and accept the 2nd invite. The screen is blank and the URL flashes quickly between the invite URL and the team URL.

**Comment by ackernaut** [comment]
### Firefox, team dash scrolls all task columns instead of single task column
Using FF, go to a team dash that has many tasks in a single column. The whole kanban scrolls instead of the single column. Not critical, but it’s a thing.

**Comment by ackernaut** [comment]
### Stuck editing state when adding/updating due date
I’m still seeing this on staging. When I add or change a due date and tap out to close, it’s stuck on editing. I have to tap on the card then tap elsewhere to get it to clear.

**Comment by ackernaut** [comment]
### Can’t edit single reflection (in prompt column) in Safari
In Safari if there’s just one card in a prompt column I can’t edit it. If there are 2+ I can edit it but in the reflection dialog.

**Comment by ackernaut** [comment]
### On Android, can’t nav to team archive
Edge case, but totally borks the app with dev error message

**Comment by ackernaut** [comment]
In the demo, you can still catch that last bot dragging a card in the air, which sticks during the vote phase @mattkrick not sure if you can disable advancing until that animation is done, too, but not the biggest deal

**Comment by ackernaut** [comment]
@mattkrick so far, of the things I noticed above, I’d say these 3 are worth looking at:

- [ ] settings views are scrollable (user profile, notifs, orgs list, org billing, org members, team integrations view [can’t see Slack panel when integrated])
- [ ] Safari single reflection isn’t editable in prompt column during Reflect
- [ ] That pesky editing state when adding/updating due date

The other issues seem like edge cases.

**Comment by mattkrick** [comment]
> Views not scrollable

fixed

> Team dash layout on mobile

made it flex-wrap. it's not beautiful, but it's a good interim as we move towards something better

> Joining teams quickly, flashing team/invite URL

while digging into this, i found the root cause of the race condition when creating a team. it always happens when you create 2 teams back to back. this was because the new auth token subscription was not renewed, so the client is no longer listening for that new auth token. this probably also caused all the "team not found" errors in sentry. 
this fix was a bit involved, but greatly simplifies our old logic.

**Comment by mattkrick** [comment]
> Firefox, team dash scrolls all task columns instead of single task column

fixed

> Stuck editing state when adding/updating due date

@ackernaut can't reproduce. any extra hints?

> Can’t edit single reflection (in prompt column) in Safari

fixed

> demo drag stuck

fixed

**Comment by mattkrick** [comment]
> On Android, can’t nav to team archive

I'm betting this'll be fixed by removing aphrodite

**Comment by ackernaut** [comment]
Not sure if I’m able to edit a card in Android, my return key makes a new line, I’m not sure how to commit the edits. When I blur the card the edits go away. (Editing a reflection card in the dialog that opens from the stack.)

**Comment by ackernaut** [comment]
Happy to report I don’t see any show-stoppers! A good round of fixes. Here’s what I got and will probably file separate issues to tackle later:
- Pesky editing state when using the due date persists [https://recordit.co/xeuE6OW44R](https://recordit.co/xeuE6OW44R)
- In the short-term we should consider disabling the ability to tap on a card during group phase for mobile. The card gets stuck on the z-index and floats in that spot during the vote phase. I’m guessing folks may try to grab a card on mobile if they’re noticing that the cards are being moved around by the bots.
- Low priority: can’t commit an edit to a reflection card in the stack dialog during reflect phase on Android, it just returns a new line, not sure how to commit
- Low priority: the mobile layout for the reflect phase could be improved when the keyboard is open (will post screenshot)
- Low priority: the reflection dialog can be tricky on mobile, especially with the keyboard open. In a long list of reflections, sometimes you can’t see the reflection you’re editing and you can’t scroll the dialog when the out-of-viewport card is focused.
