### ISSUE TITLE
Implement reactji on reflections

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#3437]
Based on #3058, my take is that we don’t reinvent the wheel on reactji affordances. I [think they are per comment/reflection](https://github.com/ParabolInc/action/issues/3058#issuecomment-565103175) not per thread/group. The only interesting idea I’ve had so far is #3438.

### AC
[See concepts in Figma](https://www.figma.com/file/GeEy1MNpxhFn9m0w9QKtOo/Reactji?node-id=1%3A14):
- [ ] A card can have multiple reactions by default
- [ ] TBD minimal menu for selecting an emoji, some options:
  - Something like https://github.com/ealush/emoji-picker-react?
  - Minimal but not good UI: use a minimal menu (like adding emoji to a Parabol task) but with a search filter at the top
  - Roll our own later that supports search, recently used, shows each group by category, and shows icons at top to jump to each category
- [ ] It shows the emoji (OS default?) and the count
- [ ] I can see when I’ve added a reaction
- [ ] Added appropriate styles, hover states on controls etc.
- [ ] Many reactji wrap if needed
- [ ] The prompt label of a reflection card, when showing, moves to the top (this would also allow us to have a top-right menu for other card interactions, an example being “Move to group” that may help with mobile usage #3187)
- [ ] Optional: [a tooltip shares who has added](https://www.figma.com/file/GeEy1MNpxhFn9m0w9QKtOo?node-id=1%3A14&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#15163031); consider optional for implementation effort, also for UX in cases where we may want anonymity
- [ ] Optional: [we offer a button](https://www.figma.com/file/GeEy1MNpxhFn9m0w9QKtOo?node-id=1%3A14&utm_campaign=team&utm_source=slack&utm_medium=message&utm_content=file_comment#15171978) to get reactions started, maybe when there’s room in the overall layout for the extra card height (e.g. reflections in a discussion thread), and a UX case for it (e.g. encouraging folks to add their reactions)
- [ ] Optional: the first reactji could be added [from a menu](https://www.figma.com/file/GeEy1MNpxhFn9m0w9QKtOo/Reactji?node-id=16%3A25) when we want default card height to be shorter (e.g. Group phase columns, if we want early reactions)

### EE
- 12 points

**Comment by ackernaut** [comment]
@mattkrick what do you think about a solution for an emoji selection menu?
>TBD minimal menu for selecting an emoji, some options:
>  - Something like https://github.com/ealush/emoji-picker-react?
>  - Minimal but not good UI: use a minimal menu (like adding emoji to a Parabol task) but with a search filter at the top
>  - Roll our own later that supports search, recently used, shows each group by category, and shows icons at top to jump to each category

**Comment by mattkrick** [comment]
looks good, another option is https://github.com/missive/emoji-mart

**Comment by ackernaut** [comment]
ah, yes I was looking for the big winner, thanks matt
