### ISSUE TITLE
Segment Event Tracking / Mixpanel Insights

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#352]
## Issue - Enhancement

Referring to one of our earliest assumed user journeys, [the corporate change consultant and team lead](https://docs.google.com/spreadsheets/d/1FdZkaHCicyTurQuT4PGlad0TCTZMg7XDz6NGI-UUubE/edit#gid=1436155632), there are some Segment events we can generate in order to gain insights into our customer adoption funnel:
- [x] A hit to the landing page
- [x] A new account is created, and step 1 of the welcome wizard is reached
  - [x] Step 1 when the preferred name is set
  - [x] Step 2 when a team is named
  - [x] Step 3 when users are invited
- [x] The first Action meeting is concluded
- [x] The second Action meeting is concluded
- [x] A second team is created
- [x] Second team members invited

Some of these are already registered with page views, others will need direct instrumentation. 
- **Estimated effort:** 3 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
fixed by #587
