### ISSUE TITLE
v4.20.0 Test Checklist

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#3528]
Active meetings
- [x] start a new meeting, then navigate to /new-meeting & try to start the same kind of meeting on the same team, you see a warning button saying "1 Active Meeting"
- [x] clicking the button shows the active meetings for that team/type
- [x] on desktop, the CTA button does not get pushed down when cycling between a visible & invisible button

Refresh checkin question
- [x] if you delete the check-in question or click the refresh button, it gives you a new one

Meeting name
- [x] team invites when a meeting is in session show the meeting name
- [x] meeting summaries show the name
- [x] event timeline show the meeting name
- [x] emails show meeting name
- [x] slack messages show meeting name

Delete user
- [x] create a new user in an incognito window. run `deleteUser(email)` in graphiql as a superuser. after logging out, the user cannot log in again. however, they can create a new account with the same email.

Multiple meetings
- [x] can start as many meetings as you want for a single team
- [x] The active meetings show up in the top dash bar & in the new meeting view when trying to start a similar meeting for the same team
- [x] if you start 2 meetings of the same kind within 2 seconds, it shows an error that the meeting was already started (should prevent accidental meetings). to test, can change DUPLICATE_THRESHOLD to 2000000 and try creating a 2nd meeting

Integrations - for whatever reason, the import order decided to start working correctly so my hack stopped. i had to refactor some things
- [x] Can add slack integration
- [x] Can add github integration
- [x] Can add Atlassian integration

Specific meeting invitation
Summary: When an invitation is created in a meeting, we try to put the invitee in that meeting. When an invitee tries to get into a meeting they don't have access to, we try to put them in that meeting. If that meeting is already ended by the time the invitee accepts the team invite, it falls back to the team dash.

- start meeting 1 on team A, then start meeting 2 on team A, go back to meeting 1
- [x] invite someone using a mass invitation while in meeting 1, that person is redirected to meeting 1
- [x] invite someone using a team invitation while in meeting 1, that person is redirected to meeting 1
- [x] User X goes the the meeting 1 URL when they are not part of the team. User Y sees a snackbar to let them in. they accept. User X is redirected to meeting 1
- [x] invite someone using a team invitation while in meeting 1, if that person is not logged in, it shows the login stuff as usual

**Comment by ackernaut** [comment]
### Notes WIP
- The meeting menu doesn’t seem to update until a refresh, at least intermittently
- I invited user C to a meeting X but the email said join meeting Y (another running meeting on the same team)

**Comment by ackernaut** [comment]
Okay @mattkrick I ran through the checklists. I’m not sure if it’s an issue with the staging environment, but it seemed like things weren’t updating on the fly, like the meeting menu when a meeting was started.

**Comment by ackernaut** [comment]
Also, the invite email didn’t know which meeting I was inviting from…not sure the rule there (use newest meeting?), and probably an edge case.

**Comment by mattkrick** [comment]
> I invited user C to a meeting X but the email said join meeting Y (another running meeting on the same team)

ah, i tried to get away with this the cheap way, but you bring up a good point. the right way to do it is to attach an invitation to a specific meetingId & then only not use that if it's already concluded

> The meeting menu doesn’t seem to update until a refresh, at least intermittently
 
forgot to include the persistFunction in the new relay config, so subscriptions were failing. great catch!
this is the root cause of the other 2 as well

**Comment by mattkrick** [comment]
@ackernaut ready for another go!

**Comment by ackernaut** [comment]
@mattkrick okay, I ran the new tests. I got mixed results:

- I still got an invite email that said Join Meeting B and redirected me to Meeting B when I had sent the invite from Meeting A
- I had a user, while trying to accept a mass invite, but signed out, get sent to the wrong meeting when signed in

Not sure if I did something wrong…but I think it would be safe to address these edge cases as an issue that doesn’t block latest getting.

**Comment by mattkrick** [comment]
> I still got an invite email that said Join Meeting B and redirected me to Meeting B when I had sent the invite from Meeting A

fixed!

> I had a user, while trying to accept a mass invite, but signed out, get sent to the wrong meeting when signed in

ahhh, the signed out piece was broken. refactored to use the same code everywhere. fixed!

**Comment by ackernaut** [comment]
@mattkrick those 2 fixes look good on staging! ✅ ✅
