### ISSUE TITLE
Markdown customizations

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#684]
## Enhancement

Let’s start a list of customizations that we would like to see to our Markdown implementation.

[GitHub inspiration](https://help.github.com/categories/writing-on-github/)

- [ ] Can use `~~text~~` to strike ~~text~~
- [ ] Can use `-[ ]` and `-[x]` for usable checkboxes
- [ ] Can use `+GH#123` at anywhere in the `textarea` to create a Markdown link to the GH issue or PR on GH. This requires org/team integration setting: “Add GitHub” See #945
- [ ] Can use `=` at beginning of `textarea` to create a card using a template. This requires card templates `{ title, content }` that can be managed by team/org. The `=` would trigger a menu with autocomplete where the user can type strings from the card template title and/or content. See #691
- [ ] Can use `#` to trigger a menu with autocomplete (see #693) where a user can multi-select existing labels per team. Pressing a space after the `#` would close the menu as a user may want to be formatting an `h1` heading. See #674 
- [ ] Can use `:` to trigger a menu with autocomplete (see #693) and select an emoji (see #303) 

**Estimated effort**: 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))
