### ISSUE TITLE
First-Time Tips

### ISSUE THREAD

**Issue by tayamueller** [ParabolInc/action#723]
## Issue - Enhancement

First-time users/first meetings need more guidance; particularly if they're not familiar with stand-ups, agile, or Trello.

- [ ] Check-In - First time modal that coaches on the purpose: “Give each team member a moment to answer this week’s Check-In Round question.”
- [ ] Updates - needs copy here explaining what this is b/c it will always be blank at the first meeting. Suggestion: "Welcome to the Updates round! This is an opportunity for each team member to briefly review their cards in each column, for the whole team. Teammates: please listen carefully and start populating the Agenda as you think of things. Be sure to keep your Updates quick; discussion will happen next when you process the Agenda together."
- [ ] Extra credit: Recommend that the above prompts show up for the first 3 mtgs, to make it all “sticky”
- [x] Agenda - folks are still having a hard time finding this on their own when they land on the "Whatcha need" screen. Something visual needs to happen to highlight the Agenda type-box--quick glow, etc? see #625 
- [x] Lobby - covered in #716 edits
- [x] Check-In - covered in #717 edits
- [x] Agenda processing - see #722

**Comment by ackernaut** [comment]
I would like to design a collapsible “Facilitator’s Notes” that is evergreen for each section.

I like Taya’s keen idea on making it show for the first 3 meetings. Maybe the notes show on a splash page before each section, or a modal.

After that I think we could reuse it by having it in a handy, but in a secondary place. Any team member can pop it open (to learn or refresh on the process). Perhaps it is a noticeable (intentional, not tiny) help icon in the Sidebar or instead the Meeting Prompt?

We could reuse this pattern for an optional #330 Metrics Review phase and/or Checklist Review phase…

**Comment by jordanh** [comment]
Iceboxing – likely resolved by holistic onboarding design
