### ISSUE TITLE
Tag enhancement implemented

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#861]
## Enhancement

When a team is working on projects that span across common work themes (epics, recurring, etc.), team members want a smart tagging system so that they can tag and filter projects.

Spec:

- [x] Users can type tags anywhere in the content, beginning with a hashtag
- [x] An inline autocomplete (and automagical, I might say) menu appears (triggered by the keystroke of a hashtag) that suggests existing tags (to reduce duplicates)
- [ ] Users can click tags to filter projects by that tag (which updates the smart search bar and/or existing filter state [TBD, link here])
- [ ] Alternatively, users can filter by tags using the smart search bar and/or some other filter control [TBD, link here]

Candidates for superpowers:

- [ ] Consider the ability to enable/disable tag superpowers at the team settings level
- [ ] **#private** (see #842) makes a project only visible to the owner (consider styling the card with “private” styles [use legacy Action card colors? use a cooler incognito theme?]
- [ ] **#weekly** cards auto-move from Done back to Active, **#monthly** cards auto-move from Done back to Future (at the conclusion of a weekly meeting)
- [ ] **#priority** each team member can mark one card as their priority (signals to other team members what their No. 1 project is at the moment—if this tag has a superpower it is that it can only exist on 1 project per team member. If a user types #priority on a different project it is removed from the previous projects.) (perhaps we have a highlighted styling denoting a #priority card?).
- [ ] +#123 associates the project with another project by visible ID
- [ ] >#123 references a project blocked by the *this* project
- [ ] <#123 references a project that is blocking *this* project
- [ ] _newer idea (2017-07-26)_ what about **#snoozed-1d** or **#snoozed-2w** or **#snoozed-3m** where we append snoozed with a timeframe (1-3 + d/w/m). We could also have a custom inline menu like the link viewer/editor where users have 3 options for number and 3 options for time unit. They can type `1`, `2`, or `3` and `d`, `w`, or `m` (or select them with the click/tap). **#snoozed** filter shows all whereas **#snoozed-2w** only shows that specific timeframe.
- [ ] Adding a tag in the text of an agenda item: a card could be referenced #123 and would be the first card in the row when that agenda item is processed. See #996 

Considerations for integrations:

- [ ] GitHub, when a hashtag appears before an issue number on GitHub, it should form a link. In our dashboard should we link to GitHub or to an imported, synced copy of the issue in our own software?

**Estimated effort**: 23 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
Capturing ideas here (I imagine this will change a lot as we explore).

**Comment by jordanh** [comment]
Partially implemented, moving remainder of this issue to future epic

**Comment by jordanh** [comment]
We know this is going to come back, but we're going to ice box this for now
